### ISSUE TITLE
Some sounds are not being affected by Master or Scene sliders settings

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1005]
Some sound effects does not get affected by the Master or the Scene SFX sliders in the settings.

Steps to reproduce:

- Go to genesis plaza clouds, at 0,0
- Lower the master volume
- You can still hear the water and the birds

- Raise the master volume
- Lower the Scene SFX
- You can still hear the water and the birds

Funny thing is, if you already have the sliders down, and reenter the scene, you dont hear any of that.

Take this opportunity to rename Scene SFX to World SFX

**Comment by Landeplage** [comment]
It looks like DCLAudioSource only sets the volume at the start of a sound. If the volume is set before the sound plays, the volume is applied correctly - but after it has started playing, changing the volume has no effect. I was able to reproduce this bug in the Wondermine scene as well, so the issue is not specific to the Genesis Plaza.

However, I was only able to reproduce it in the live browser version. While testing in Unity, scene SFX do not seem to play. This makes it hard to debug. Maybe my WSSController settings are wrong? I don't think I will be able to get further without getting scene sounds to play in Unity.

**Comment by Landeplage** [comment]
Thanks to Brian, I was able to get scene SFX working in the editor - and fix the bug. Turns out I'd forgotten to subscribe to the "On audio settings changed" event in DCLAudioSource.

Also renamed the "Scene SFX" slider to "World SFX".
