### ISSUE TITLE
Builder and Builder in world unable to publish a scene

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#1066]
This scene is unable to be publishes on builder and in builder in world it stays stuck at 0%

[https://app.zenhub.com/files/337227404/9160d9b7-a206-4ac5-bc9a-9a40bda14b5e/download](https://app.zenhub.com/files/337227404/9160d9b7-a206-4ac5-bc9a-9a40bda14b5e/download)<!--

**Comment by nachomazzara** [comment]
I can import and deploy the scene without any issue. We need to check what issue the user is seeing.

**Comment by olavra** [comment]
If you import the scene in Builder web, publish it in a Land, and go to the Land, the scene is not loading some of the assets

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/642b6493-7ab0-443f-a7c3-ebe7126701fe)

But its fully loading in builder web

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/f29def80-228f-4f19-a0be-63946d9db4ee)

**Comment by olavra** [comment]
Pending of a land in prod for @Suduck in order to test the scene

**Comment by cazala** [comment]
Hi @Suduck I was taking a look. This is a scene that was created using the In-World Builder and then imported into the regular Builder right? Cos I'm seeing lots of unknown component type like `Name` and `LockOnEdit` which do not exist on the Builder. That should not break the scene tho since unknown components are ignored, but I noticed that there are several entities with the same name `test` in the `builder.json`:

<img width="627" alt="Screen Shot 2021-10-19 at 6 07 29 PM" src="https://user-images.githubusercontent.com/2781777/137991005-a939f2dc-faf7-4436-bb0c-686b1de60289.png">

That's problematic because when the Builder attempts to generate the script for either the deployment of the scene or generate a zipfile for download, it loops over all the entities and instantiates them using the SDK: https://github.com/decentraland/builder/blob/master/src/modules/project/export.ts#L177-L178

That will throw once the second entity named `test` tries to be instantiated with a `There is already an entity with name "test"` error, which won't stop the deployment/export per se since it is wrapped in a try/catch block, but it will skip those entities for the scene, that's why there are some parts of the scene missing.
