### ISSUE TITLE
Any running animations need to be stopped before playing a new one

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#107]
If I play an animation and then I want to play another animation, or the same animation again, I need to first explicitly stop the last played animation. It's a very common newbie pitfall, they aren't able to play an animation a second time, and the reason is that they need to stop the animation explicitly before they call it again.

This doesn't work

```ts
sit.play()

Input.instance.subscribe('BUTTON_DOWN', ActionButton.POINTER, true, (e) => {
  sit.play()
}
```

When dealing with a model that has several animations that may have ben called before, the workarounds needed for this can get really nasty.
See this example:
https://github.com/decentraland-scenes/Block-dog

Here you need to explicitly stop all these animations every time before you want to play another one
    sit.playing = false
    stand.playing = false
    walk.playing = false
    drink.playing = false
    idle.playing = false
    stand.playing = false

This issue has been around ever since we migrated away from Babylon. Back when HardlyDifficult did the escape room tutorial (April 2019), he avoided mentioning the workaround for this bc it was a bug we were supposedly going to fix by the time the videos were released.  ....sure.

**Comment by kuruk-mm** [comment]
To fix this issue we decided to implement `layers`

With `layers` we can decide which animation can be played invididually or at the same time.

I tried to implement `layers` at renderer level, but I instantly started having problems:
Kernel and Unity get out of sync when I send a `play` event in one Animation. Because Unity stop all other animation states in the same layer and doesn't report it to the Kernel.

So to avoid this problem, I propose to implement all layer behavior in the kernel, and we just notify Unity about changes in `playing` when is needed. I will post a PR with this approach.
