### ISSUE TITLE
Integrate GPUSkinning to scene skinned meshes (GLTFShapes and ABs)

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1088]
We should implement GPU Skinning for scene meshes (currently is only running for avatars) so that the skinning is done in the GPU through a shader instead of in the CPU.

These 2 GPU Skinning for avatar PRs may come in handy:
https://github.com/decentraland/unity-renderer/pull/1041
and
https://github.com/decentraland/unity-renderer/pull/1140

Tasks:
- [x] Update `SimpleGPUSkinning.cs` to allow configuring which 2 UV channels (0..7) are to be used for passing the bones that into the shader.
- [x] Integrate the `GPUSkinning` shader calculations to every relevant pass in the Lit shader. If a unitypackage shader code is used for a pass, duplicate it locally and customize it.
- [x] Fix SSAO visual artifacs.
- [x] Deal with "mesh bounds" issue. [Configured enormous bounds for non-avatars since we are not culling animations]
- [x] Debug issue with broken gigantic meshes, some are skinned correctly, some don't. [The problem was scenes using skinned meshes and non-skinned meshes with the same material, so when we enabled the GPU_SKINNING keyword for those `sharedMaterials` the gpu skinning would run for non-skinned meshes and break their vertices]. Changed `sharedMaterials` usge for `materials` but that breaks our previous optimization to share materials between meshes
- [x] Move GPUSkinning to another intermediate class or place (maybe GLTFshape class?) instead of DCLAnimator, since many GLTFShapes don't have the Animator component and thus wouldn't be affected by GPUSkinning when that happens
- [ ] Implement way of keeping the "shared materials" optimization for GPUSkinned meshes [Sometimes the same material is being shared between non-skinned meshes and skinned meshes, and sometimes between more than 1 skinned meshes but having different armatures... those cases break the GPU Skinning]
- [ ] Compare performance in heavy-skinning scenes (casino, soho plaza)
- [ ] Deal with calculating the mesh bounds: maybe let the SkinnedMeshRenderer run for a frame and get that data before replacing it? [We can't just set giant bounds because the SceneBoundsChecker hides the mesh in several cases]
- [ ] Find a way of avoiding wearables GPUSkinnig Setup on the GLTF Loading pipeline for wearables, as that setup is done in the Avatar Renderer pipeline
- [ ] Patch ABs material on their loading to match the materials CRC change regarding GPU_SKINNING keyword
- [ ] Fix "shiny" artifacts seen on meshes, probably normals problem when applying GPUSkinning in the shader.
- [ ] Deal with re-generating an entity's meshesInfo when we swap its SkinnedMeshRenderer for a regular MeshRenderer ?
- [ ] Apply GPUSkinning to Unlit shader
- [ ] Solve conflicts with master branch and the AvatarRenderer refactor
- [ ] Fix tests

**Comment by pravusjif** [comment]
### Branches involved
* `feat/DCLAnimatorGPUSkinning`: https://github.com/decentraland/unity-renderer/pull/1628
* `fix/GPUSkinningSharedMaterialAndAffectedGLTFShapes`: https://github.com/decentraland/unity-renderer/pull/1704

### Conclusion
After a month into this enormous implementation **we decided to stop because the performance metrics don't show promise at all, we don't want to fall into a sunk cost falacy**:
- Performance comparisons in tominoya casino [-118,134] (pepe NPCs are skinned GLTFShapes) using our performance meter tool:
    - WITH GPUSkinning, sharing materials between SkinnedMeshes with same armature and between non-skinned meshes:
        - https://play.decentraland.org/?renderer-branch=fix/GPUSkinningSharedMaterialAndAffectedGLTFShapes&DISABLE_ASSET_BUNDLES&LOCAL_COMMS&position=-118%2C136&realm=dg&LOS=0
        - PerformanceMeter - Data report step 2 - Processed values:
          * PERFORMANCE SCORE (0-100) -> **38.21 <---- !!!**
          * average FPS -> 17.71014
          * highest FPS -> 19
          * lowest FPS -> 10
          * 50 percentile (median) FPS -> 18
          * 95 percentile FPS -> 19
          * total hiccups (>0.05ms frames) -> 456 (82.61% of frames were hiccups)
          * total hiccups time (seconds) -> 25.27587
          * total frames -> 552
          * total frames time (seconds) -> 30.03182
         
    - WITH GPUSkinning, not sharing any material used for GPUSkinning (using `materials` instead of `sharedMterials` in the `SimpleGPUSkinning` class):
        - https://play.decentraland.org/?renderer-branch=feat/DCLAnimatorGPUSkinning&DISABLE_ASSET_BUNDLES&LOCAL_COMMS&position=-118%2C136&realm=dg&LOS=0
        - PerformanceMeter - Data report step 2 - Processed values:
           * PERFORMANCE SCORE (0-100) -> **21.55 <---- !!!**
           * average FPS -> 12.85679
           * highest FPS -> 14
           * lowest FPS -> 10
           * 50 percentile (median) FPS -> 13
           * 95 percentile FPS -> 14
           * total hiccups (>0.05ms frames) -> 404 (99.75% of frames were hiccups)
           * total hiccups time (seconds) -> 29.90681
           * total frames -> 405
           * total frames time (seconds) -> 30.00681
        
    - NO GPUSkinning, what we have in production, sharing materials between skinned and non-skinned meshes normally
        - https://play.decentraland.org/?DISABLE_ASSET_BUNDLES&LOCAL_COMMS&position=-118%2C136&realm=dg&LOS=0
        - PerformanceMeter - Data report step 2 - Processed values:
           * PERFORMANCE SCORE (0-100) -> **86.37 <---- !!!**
           * average FPS -> 23.21348
           * highest FPS -> 24
           * lowest FPS -> 15
           * 50 percentile (median) FPS -> 24
           * 95 percentile FPS -> 24
           * total hiccups (>0.05ms frames) -> 33 (4.63% of frames were hiccups)
           * total hiccups time (seconds) -> 1.983994
           * total frames -> 712
           * total frames time (seconds) -> 30.03082

### Main problems encountered
- The main problem is **materials sharing**: for GLTFShapes, if we enable GPUSkinning (requires enabling a special keyword in the material), we have to stop sharing materials between skinned and non-skinned and we have to stop sharing materials between different-armature skinned meshes. By losing the shared materials optimization we degrade the performance more than what we gain from the GPUSkinning on GLTFShapes. For avatars this is not a problem because avatars [don't share materials](https://github.com/decentraland/unity-renderer/blob/ac6f1b381bf3f4f8ce70096a7f3267d7037e8dbf/unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombinerUtils.cs#L122). Also, if a material is hared between same-armature skinned meshes, the animations played that update their skinning will be applied to every instance of the material at the same time...
- **Mesh bounds calculation**: we didn't find a reliable way to calculate the animated mesh bounds, and hardcoding giant bounds (that may always cover the whole mesh) naturally introduces problems with the SceneBoundsChecker. For avatars this works because they have always the same bounds so we have those hardcoded. 
- There could be probably more problems found deeper into the rabbit hole.

### Implementation details
A more detailed recount of what's been implemented during this month of implementation (had to pause several times to debug other unrelated issues of the renderer):

- Scenes used for testing with skinned meshes:
    - Shark sccene: ropsten 58,-70
    - Genesis plaza: mainnet 0,0
    - Tominoya casino: mainnet -118,134 (.org or NPCs and many meshes are not spawned by the scene)

- Implemented same GPU Skinning code used in avatars Toon shader, in our lit shader and the relevant passes (unlit shader pending)

- Revised uv/texcoords already used in our Lit material and between vertex and fragment shaders
    - Found out that we can use up to 16 interpolator variables between the vertex programs and fragment programs. But we are limited to using the TEXCOORD from 0 to 7 as input tex coords for the vertex programs (AKA using Mesh.SetUVs() from C#).
    - We already have the needed 2 free TEXCOORDs to send the bone data to the shader
 
- Applied GPUSkinning to pragma target 2.0 subshader
    - Tested commenting target 4.5 subshader, it can only be tested in-build, it works.

- Had SSAO issue, fixed with mini-patch resetting `output.normalWS` in DepthNormals pass.
    
- There's still some issue with normals because GPUSkinned meshes look shiny, should be tackled later

- Setting the mesh bounds is a problem because we can't know the constant bounds change of the animated mesh
    - If we hardcode giant bounds that should cover every possible skinned mesh (since we don't have animations culling) we introduce problems with the SceneBoundsChecker. Discovering what disabled the renderers took several days of debugging due to a bug in Rider in macOS (and Kernel turning off the SceneBoundsChecker when killed who knows why).
    - For avatars that's not a problem because they all have the same armature and size so we have hardcoded bounds that work for all avatars
    - We could try letting the SkinnedMeshRenderer run for a couple of frames and try getting its calculated bounds before swapping it for a MeshRenderer

- Some GLTFShape are skinned but don't use our DCLAnimator (since the SDK component hasn't been attached to the entity in those cases)
    - Having the GPUSkinning setup in the DCLAnimator as originally intended won't be enough
    - Moved the GPUSkinning setup to `AssetPromise_GLTF.OnAfterLoadOrReuse()` and the skinning update in `Skinning update en InstantiatedGLTFObject`. Tried several other places (including `GLTFSceneImporter`) but couldn't find any point in the GLTF loading pipeline that would setup the GPU Skinning for the master object in the Asset Promises Library (Pool) and then have the other pool instances copying that.
    - Ideally we should be setting up the GPU Skinning in the master asset of the asset library (for GLTFs and AssetBundles) so that every copy made has the updated version of the asset

- We have to evaluate how these changes affect Asset Bundles
    - The farest we got into this GLTFShapes GPU Skinning implementation was done only with GLTFs to avoid overcomplicating things (`DISABLE_ASSET_BUNDLES&DISABLE_WEARABLE_ASSET_BUNDLES`).
    - If we apply changes directly in the `GLTFSceneImporter` (for example for enabling the GPU Skinning keyword for materials constructed for skinned meshes) then it most definitely would affect new AB conversions, and ABs would require some kind of patching in runtime to cope with those changes.

- Observed several NPCs in Genesis Plaza whose meshes got completely broken while their GPU Skinning was getting updated
    - It took several days of debugging to find out that the problem was triggered when using `sharedMaterials` instead of `materials` (local instances for each mesh) in the `SimpleGPUSkinning` class.
    - After that I found out that there were certain materials being shared between skinned meshes and non-skinned meshes, as well as materials being shared between skinned meshes that had different armatures
    - Enabling GPU Skinning for those shared materials, while keeping sharing them triggered the broken meshes bug.
    - In the end I implemented a solution that avoids sharing materials between skinned and non-skinned meshes (added an offset to the materialIndex used when constructing and caching the material in `GLTFSceneImporter`), as well as between skinned meshes with different armature (calculated an int hashcode from the array of bones of skinned meshes and used that with their CRC caching). Unfortunately even having that most-possible-shared materials performs worse than just using regular SkinnedMeshRenderers and keep sharing all materials.
    - Some materials used for debugging filtering by name:
        - 2 NPCs talking about art: material "AvatarSkin_MAT"
        - bar NPC with glasses: material "AvatarWearable_MAT"
    - Found another problem when sharing materials between skinned-meshes with same armature: whenever the shared material is updated with its skinning, the changes will be applied to all meshes using that material at the same time... making this apporoach totally unusable. By that point I thought we had that somehow solved for avatars and that they were sharing materials but then found out that wasn't the case.

- Had problems with wearables breaking when setupping the GPUSkinning in `AssetPromise_GLTF.OnAfterLoadOrReuse()`, so I had to add a new `applyGPUSkinning` bool in `AssetPromiseSettings_Rendering` to filter that setup for Avatars in the `WearableController`, because the GPU Skinning for wearables is done in the AvatarRenderer pipeline.

- Later found out that the GPU Skinning material keyword enabling I did in `GLTFSceneImporter` actually messed the materials that were later used by the AvatarRenderer pipeline, so that should be moved elsewhere
    - Maybe the whole material setup could be moved from the `GLTFSceneImporter` into `SimpleGPUSkinning` itself and use the material cache in there as well.
