### ISSUE TITLE
Hologram material is never destroyed after loading some GLTF assets

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1191]
Thread
https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1631597934169100

**Comment by pravusjif** [comment]
Thanks a lot! I kept investigating from where you left off and it turns out you were right about the pooling problem.

The problem is we have [a timed bailout](https://github.com/decentraland/unity-renderer/blob/3489c6f803b231eee9fba41e3aa4b1b776436e1a/unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs#L320) when the `GLTFSceneImporter` waits for the `MaterialTransitionControllers` to finish on the GLTF. So GLTFs that take more than 5 seconds to load are going to skip waiting and continue the flow that will end up saving that master asset in its asset library (a pool) with the `MaterialTransitionController` (ergo the hologram material) still on.

(This issue also taught us that when a GameObject is cloned, the cloned GO monobehaviours don't call their `Awake()` they just call their `Start()`)

Removing that timed bail solves the issue. Apparently this also fixes the problem that sometimes displayed materials as broken-pink.

Created [this PR](https://github.com/decentraland/unity-renderer/pull/1195) with the fix, @AjimenezDCL check it out and change it as you please, maybe you can think of a possible test to add? or maybe we can do it in another PR. If you think it's ready let's flag it as RFR.

**Comment by AjimenezDCL** [comment]
@pravusjif Awake is being called though, check the logs above.

**Comment by pravusjif** [comment]
Weird, in my debugging I definetely logged that the cloned object only had its `Start()` call, anyway it's not harming us in any way now =)
