### ISSUE TITLE
Add custom postprocessing for Explorer Desktop

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1669]
Taking advantage of the new power that the desktop application can offer us, it would be nice to be able to use a different postprocessing that includes depth of field, vignette, grain, etc.

- [x] Add new post-processing stack for Desktop only.
- [x] Add new settings to disable depth of field in graphics.

**Comment by ShibuyaMartin** [comment]
Some of the basic post processings that would be cool add to the desktop client are:

- Depth of Field
- Color Adjustments
- Vignette 


Made some tests in order to compare both results and the difference is quite noticeable! I think it gives a more crisp, vivid and cinematic feel to the client.

1)
NO POST
![1-no post.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/b005d681-5135-4b1d-8b2a-94df42b9a720)
POST
![1-post.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/7f08f238-ad34-464c-9788-24f07d2046a7)

2)
NO POST
![2-NO POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/99f857d3-b5f1-4cab-8c02-afea98cb5153)

POST
![2- POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/f65c48bb-bdfe-42c8-a1e9-4303f2579379)

3)
NO POST
![3 -NO POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/ac1eb08b-7fab-48bb-b614-4127ef498b09)

POST
![3- POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/4bccec6e-3fb9-457e-836b-c1ea2a45ea36)

4)
NO POST
![4 NO POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/132df719-4621-4d65-b69b-225ea9b13e2f)

POST
![4 POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/f902dafc-08f0-4039-81b7-a1e1024b3568)

5)
NO POST
![5 -NO POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/547071fb-67bc-4f40-8680-c71c62bba8d5)

POST
![5- POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/09db51ea-0560-43ad-a22b-50fa16677d11)

6)
NO POST
![6- NO POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/b9d9b17d-ec48-4671-97f3-e4940d8d7115)

POST
![6- POST.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/4c2ef912-12b8-4f4c-88d5-948a7a1a3eef)

Values
![Screen Shot 2022-01-06 at 00.00.17.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/082fd2ed-0a9d-46fc-86aa-239b680f7cb8)

**Comment by ShibuyaMartin** [comment]
Values to change in PPVolume:

### Overrides:

**Depth of Field**
Mode: Gaussian
Start: 50
End: 300
Max Radius: 1
High quality Sampling: ON

**Color Adjustments:**
Post Exposure: 0.5
Contrast: 5
Saturation: 3

**Vignette:**
Color: #000
Intensity: 0.25
Smoothness:0.2

**Comment by lorux0** [comment]
I will block this issue until visual improvements becomes a priority in desktop project

**Comment by lorux0** [comment]
Research documentation: https://www.notion.so/decentraland/Depth-of-Field-459f9ca7db27408c89c59ac1bf5ebe1e

**Comment by lorux0** [comment]
here is the current progress of the feature: https://www.notion.so/decentraland/Depth-of-Field-459f9ca7db27408c89c59ac1bf5ebe1e

**Comment by xavi-dcl** [comment]
Follow up issue: #3951
