### ISSUE TITLE
Investigate how to fade in/out UIs as a single mass

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#1781]
Fade In / Fade out animation of the menu does not fade the whole menu as a single mass, but with different transparencies for the header, the buttons etc.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/4b0bc304-8618-4422-a131-6b7fac1f7b4c)

**Comment by JuanSalice** [comment]
Using a canvas group produces the same effect that changing each individual alpha. Which it is not desired.
In order to achieve the desired effect, the best approach is using a render texture of the whole menu and changing the alpha of that render texture. 
This implies creating a new camera to get the render texture which it is not ideal, and it could be incompatible with the changes that the UI needs to implement the blur effect.
