### ISSUE TITLE
Analyze the WebRequests timeout

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1809]
Currently, we have some requests with 5000 thousand SECONDS of timeout. That's is 1 hour and 23 minutes.

And other requests with no timeout at all.

We must check if the timeout happens when we're downloading the content or it happens when the server doesn't respond at all.

And then decide if we're going to put some timeouts to the requests and how much time.

### Acceptance Criteria
- [ ] Make proposal document to Mateo
- [ ] Implement solution

**Comment by dalkia** [comment]
Webrquests are being done using the `Environment.i.platform.webRequest` variable.  Using the Get method, you can create a new web request. 

The default timeout time for this request is 0; and there are cases in which 15, 10, and 300 are set. (`WebRequestLoader.cs`, `DCLAvatarTexture.cs`, `GifDecodeProcessor.cs`)

The cases in which is 5000 are in class `WearableFetchingHelper.cs`, in methods:

`GetThirdPartyCollections()` => 
`EnsureCollectionsData() ` => Not longer being used, since the collections data is now controller by the `CatalogController.cs`.
`GetWearableItems()` => Not longer being used, since the collections data is now controller by the `CatalogController.cs`.

This were the only scenarios in which the 5000 time was used. Since this is an old issue, probably the requests that were required to ba analyzed are no longer used.
