### ISSUE TITLE
Avatar in backpack does not have posprocessing effects

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1838]
The camera rendering the avatar of the backpack does not have the same postprocessing profile than in world, skipping bloom, ambient occlussion, color correction etc.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/e40e7c45-57d0-40aa-9bd4-bf7ddc322b60)
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/e759a900-2dfe-4ddc-8c69-b8e68105edba)

**Acceptance Criteria**
- [ ] Avatar in backpack is rendered using the same effects than in-world

**Comment by DavideJensen** [comment]
I already made some changes in the PR: #1855 the problem is that the post processing stack has some issues with the transparency.
I had to change the render texture color format to R16G16B16A16_SFLOAT because the previous one didn't support the bloom effect, I then enabled the post processing effect and set the proper volume layer in the preview camera.
The issue now is that the solid color alpha is not considered for the transparency anymore, this has been a known issue and there are various post online of people manually changing the shader code to restore the alpha. It also appears that the colors are slightly darker:

![Screenshot 2022-01-28 at 10 47 45](https://user-images.githubusercontent.com/4254522/151526236-d5386817-a048-4509-aac6-29fa3f8de0c7.png)

![Screenshot 2022-01-28 at 10 47 59](https://user-images.githubusercontent.com/4254522/151526127-6e31f9cd-78c8-4c53-942b-2d38231de43b.png)

I'd ask the support of @BrianAmadori or @lorux0 to go on with the issue
