### ISSUE TITLE
Texture compression performance

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#1867]
Problem: Texture2D.Compress is very slow, freezes the main thread, and can't be run on a worker thread.

~~Solution: Search for a fast open-source texture compression library that can be run on a thread, potentially fixing hiccups on both WebGL and Desktop platforms.~~ (unity already uses a fast one but that's not enough)

Solution2: Compress all textures before uploading to content servers.

**Comment by pravusjif** [comment]
Did some profiling with the desktop client and the `Texture2D.Compress()` process continues to be the heaviest hiccup-culprit when exploring the world:

![Unity_okertmXgP9.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/0cad531d-bbb6-48ce-9a8a-20044854a451)

![Unity_zkJQSMtFVw.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/d5b8a990-1b3a-4cfb-bad9-87bd8725a0d7)

Possible solutions/improvements:
1. Since we see several calls in the same frame for the `Texture2D.Compress()`, we may be able to throttle those compress calls to be spreaded through multiple frames, thus reducing the impact. This is the first thing I want to try.
2. Test how does the desktop client behave if we avoid compressing altogether, although it will have an impact on the memory used
3. After researching a bit I found a user post that mentions a way of loading textures without blocking the main thread, although it looks like he uses asset bundles so I don't have much faith on the solution but might as well try something similar out: https://stackoverflow.com/questions/69139083/texture2d-loadimage-async
4. Another alternative that could be explored is trying the compression in the GPU using a Compute Shader as suggested in [this thread](https://forum.unity.com/threads/fast-runtime-texture-compression.1123450/) although doing that has several limitations that probably would keep us from using that approach.
5. According to [this other thread](https://forum.unity.com/threads/runtime-texture-compression-using-compute-shader.1031014/#post-6677602) a Unity Dev mentions that from Unity 2021.1 the `Texture2D.Compress()` has been updated, maybe it improves our runtime case as well, we'll see when we update the whole project

**Comment by pravusjif** [comment]
- Tested spreading tex compression between frames in https://github.com/decentraland/unity-renderer/pull/1972 but there are almost no effect besides making models loading slower, so for now we decided to close that PR. It still has a frames spreading UI slider in the PR for debugging purposes in case we want to test it again in the future.

- Instead of spreading, we will disable compressing for the desktop client, as that proved to be better when testing

- We'll try to tackle the textures resizing hiccups on GLTFs parsing by replacing [`Texture2D.ReadPixels()` and `Texture2DApply()` ](https://github.com/decentraland/unity-renderer/blob/0fbecaf0677cbee04418af97ba7aba74ba242c47/unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/TextureHelpers/TextureHelpers.cs#L45)with [`Graphics.CopyTexture()`](https://github.com/decentraland/unity-renderer/blob/0fbecaf0677cbee04418af97ba7aba74ba242c47/unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/TextureHelpers/TextureHelpers.cs#L57)

**Comment by pravusjif** [comment]
Tackled with these 2 PRs:
- https://github.com/decentraland/unity-renderer/pull/1981
- https://github.com/decentraland/unity-renderer/pull/1982
