### ISSUE TITLE
Can't see what I write into the chat box

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#20]
This is an issue that has been happening randomly ever since we have had chat in the world.
One out of every 10 times or so that I try to write a new message into the chat window, my text appears in a white font instead of black, and I can't see what I write because it's invisible against the background.

I can't see if I did a typo, so I don't know what I'm sending until I hit send, which is really bad as a chatting experience.

I don't know how to reproduce this, it just happens randomly, but I'm sure you've all experienced it a LOT of times. It's not on the first message I send, I think you need to be engaged in a conversation before it happens.

**Comment by olavra** [comment]
@nearnshaw is this still happening to you?

**Comment by nearnshaw** [comment]
I didn't run into it in the last month or so, before that yes

but also I didn't chat as much in-world to know for sure

**Comment by sandrade-dcl** [comment]
I have tried to reproduce this issue but have not been able to do so. I have also checked the code flow related to this HUD and there is not anything changing the text color, hidding it or anything else...

My theory is that, in some point in the past, we had set the material preset of the text input component as `SF-UI-Text-Semibold SDF Material` instead of `SF-UI-Text-Semibold SDF Material` as currently. In this case, it would provoke the hidding of the text in some operative systems or browsers (it already happened in the past with the avatar names). Could it be @RominaMarchetti?

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/ed29ccdb-5e2e-4702-a325-74b369f24223)

For now we are going to close this issue as `NOT REPRODUCED` and if it comes back again in the future, we will have to take a look more in deep.

**Comment by sandrade-dcl** [comment]
@nearnshaw do you remember the specific configuration did you have when you reproduced it? (operative system and browser basically)

**Comment by nearnshaw** [comment]
thanks for checking this
in the past when I ran into this, it was always in Chrome and on a mac

I haven't seen it happen again for a while now
although there was no apparent pattern for when it happened, so I can't assure it's gone
but I think we do well in assuming it got fixed at some point

**Comment by sandrade-dcl** [comment]
> thanks for checking this
> in the past when I ran into this, it was always in Chrome and on a mac
> 
> I haven't seen it happen again for a while now
> although there was no apparent pattern for when it happened, so I can't assure it's gone
> but I think we do well in assuming it got fixed at some point

Ok, then we close it and will be attentive. Thanks!
