### ISSUE TITLE
Wallet connect and metamask interactions are different (some WC don't even work)

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2004]
- The wallet interactions freamework/API should be wallet-agnostic
- Apparently that's not the case right now, for example the experience of signing into the GoltfCraft (https://play.decentraland.org/?position=48%2C-45) scene is completely different (and is broken with wallet connect):

Signing with Metamask:
![Screen Shot 2022-03-16 at 18 42 25](https://user-images.githubusercontent.com/1031741/158697502-374be527-fef2-4a72-a40e-7827f1e26be6.png)

Signing with Wallet Connect:
![Screen Shot 2022-03-16 at 18 46 01](https://user-images.githubusercontent.com/1031741/158697560-6a62344d-b967-4b45-94af-87388df486b0.png)
![Screenshot_20220316-184636](https://user-images.githubusercontent.com/1031741/158697618-1754cf6d-f782-4f32-8fd9-1842d6da440e.png)

Even if we have that extra pop-up warning when being logged into Decentraland with Wallet Connect, the signing and transactions should all work regardless of the wallet.

**Comment by pabloes** [comment]
For now we use @decentraland/web3-provider
and eth_signTypedData_v4
![image](https://user-images.githubusercontent.com/2302722/158926278-2f60b14b-5b25-4c45-b55c-20dbee4a83fc.png)

**Comment by nachomazzara** [comment]
Hi, @pabloes can you share a repo and how to reproduce the issue? I need more context about the library versions, their usage, etc

**Comment by pabloes** [comment]
The problem here is not about decentraland or wallet-connect, it's about wallets supporting RPC method "eth_signtypeddata_v4"

But this EIP-712 is not "Final", and only some wallets support it:
- Metamask
- Metamask mobile
- Rainbow

But not TrustWallet for example.

I liked its UX and seeing that metamask adopted it, I just used it also.
The only we need to work as always is to still have access to the provider sendAsync method to be able to send "eth_signtypeddata_v4" RPC, but EIP-712 signatures with walletconnect wallets not supporting it, won't work.

If something is broken in decentraland for us we will apply a migration, but it's working fine right now as always with the mentioned wallets, I always had in mind a migration in future btw. Currently we don't verify the signature/wallet on a backend, we just use the signature as a fingerprint with a third party cloud service (playfab).

**Comment by pabloes** [comment]
a mistake in previous message, it is not that TrustWallet doesn't support eth_signtypeddata_v4, is that we have something wrong on our RPC message.

**Comment by pravusjif** [comment]
Thanks for all the info and testing on your side Pablo, so the problem lies in the usage of ` eth_signtypeddata_v4` method in the scene code (with `@decentraland/web3-provider` library), as apparently if the RPC message hasn't been configured correctly then some wallets with wallet-connect (in this case TrustWallet) can have problems on their signing interactions.

This way of using that method in the marketplace should be a good example of how it should be used to work wallet-agnosticly:
https://github.com/decentraland/marketplace-contracts/blob/d27b695e8006e70a5b7f245a57a13a5ec97f7ccf/test/helpers/metaTx.js#L68
