### ISSUE TITLE
A gray screen appears for a short time each time you open or close the map

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#2071]
https://images.zenhubusercontent.com/337227404/a3b615b3-ab5d-4b66-87b7-5ae713fb89b4/2022_03_25_14_49_05.mp4

**Comment by popuz** [comment]
This problem is caused by SectionContent Image (1) being displayed before the NavMap content (2) on enabling map (and vice versa for disabling). In disabling lag is less, because it happens almost in one frame, but for enabling the lag is much more visible because NavMap content is shown after it gets all the data (so more frames are needed). Same behavior (bug) exists when you switch between tabs Map<->Bagpack<->etc., however there it is not so visible, since you are still inside UI
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/ff1d46e8-ecd1-4e05-a668-3b01ba5fe83f)

**Comment by popuz** [comment]
Solutions are more design related:
1. We can wait until Map content is loaded and only then show the Map (but it could feel not so UX-friendly)
2. We can try to fadeIn/Out alpha of the SectionsContent Image, so the transition is more smooth. keep in mind it is still needed for the Mask behaviour, so full zero of alpha will not work properly. Also, there is a RadialGradiant in place which then should follow same behaviour.
3. Maybe design can propose some better approach :) 
@JorgeDecentraland  @lorux0 , what do you think guys?

**Comment by JorgeDecentraland** [comment]
@RominaMarchetti maybe you can provide some feedback after the previous comment from @popuz, please?

**Comment by popuz** [comment]
@RominaMarchetti, thank you for your answer. One question, should this logo Image be shown for both situations -when opening Map from the world (i.e. HUD was in hiding mode at the moment of the call) and when opening by switching tabs (i.e. HUD was in show mode at the moment of the call. For example, when switching from Backpack to the Map)? Or only for the first situation, since in transition from Backpack to Map this grey screen flashing is not noticible...

**Comment by RominaMarchetti** [comment]
@popuz for both situations :)
