### ISSUE TITLE
After unloading and re-loading genesis plaza, the NFTShapes are not re-instantiated

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2099]
Repro steps:
1. start in Genesis Plaza
2. walk to -20, 0 so that the scene is unloaded
3. walk back to 0,0 and check that the NFTShapes are not instantiated in the gallery.

Sometimes it doesn't happen but I was able to reproduce it 2/3 times.

https://user-images.githubusercontent.com/1031741/160705257-d14a8008-d3de-458b-9e22-c37d4bb3ad85.mp4

No new/weird errors were observed in the browser console

**Comment by Suduck** [comment]
The system is working in the renderer, seems to be a problem with the code scene itself, the content team should handle it

**Comment by davidejensen** [comment]
I confirm what @Suduck said. the unity-renderer is not getting the scene message SHARED_COMPONENT_ATTACH that instantiates the prefab for NFTShapes.
There is a strange behaviour because going just a bit far away doesn't trigger the re instantiation when coming back, but going really far and coming back sometimes triggers it.
More than platform I think it's a kernel problem because it's happening in all scenes and not only this one.

**Comment by davidejensen** [comment]
Was discussed on Slack and fixed by the sdk team. It was related to the lazy loading scene code, closing.
