### ISSUE TITLE
Implement blur effect for top header subsections

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2183]
Some elements of the UI require an effect that blurs whatever elements they have behind.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/ed95182e-03df-423c-8ef9-05603e3b095b)

**Comment by JuanSalice** [comment]
Planning for a restructuring of the UI is needed before advancing on implementation.
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/35297896-1e37-4221-baf5-c41ec728f1e1)

**Comment by sandrade-dcl** [comment]
After the meet we have had @JuanSalice, @lorux0 and me about how to integrate the bluf effect in our UI, we have reached the next conclusions:

1. Juan is going to **create and configure an `UI Camera`** that will be used for all our UI canvas.
2. We will need to create some kind of **reference to the new `UI Camera`** in order to be accessed from our code.
3. **All the UI canvas in our client should be modified** in order to change its `Render Mode` from `Screen Space - Overlay` to `Screen Space - Camera`. Once it is set to `Screen Space - Camera`, we will have to set the `Render Camera` with the `UI Camera` created in the step 1. This assignation will be done dinamically usaing the reference created in the step 2.
4. **The same for the UI canvas used for the scenes**.
5. We will have to **take care about the `Mouse Catcher`** game object because it wont let us click in the UIs with the new canvas configuration.
6. From this point on, for new UI prefabs that we need to create, **we will use a non-canvas parent that will contain the needed canvases** (as minimum one configured as `Overlay` and, depending on the needs, we could have another one configured as `Camera`). This parent game object will contain components like the `Animator` or the logic script related to the UI Component view.

**Comment by JuanSalice** [comment]
- Blur implementation is ready to be made, but some changes are needed in the main menu prefab

**Comment by MichaelBitsakis** [comment]
Applied BlurRT UI Image Element shader to AvatarEditorHUD --> Header

![Explorer.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/98dae480-bcff-41bb-b85b-543fe82a4eb0)

![explorer_Header_Blur.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/022107e5-4205-408a-a8a4-1cb23385eba7)
