### ISSUE TITLE
Upgrade Test Framework to support async tests

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#2189]

**Comment by davidejensen** [comment]
Putting a high estimate because I'm not certain on the complexity of this untill I research further the current structure

**Comment by davidejensen** [comment]
Quick note, async tests require the version 2.0+ of the Test Framework, those versions are experimental still. Of the available ones there is 2.0.1-exp.1 2.0.1-pre.18 and 2.0.1-pre.12, will try with the exp.1 that is considered more solid

**Comment by davidejensen** [comment]
We have decided to postpone this upgrade to the future after the initial tests, following a brief description of the findings

### Test framework version
The unity test framework supports async tests from the version 2.0, the problem is that the currently available downloads are the following 3:
* 2.0.1-exp.1
* 2.0.1-pre.18
* 2.0.1-pre.12
All three of those are in experimental status and not yet ready to full usage.
The tests have been made with the 2.0.1-exp.1 that is considered the most stable.
After the Test Framework update there was a second module update required, the Performance Test Unity package because internally it wasn't working with the new test framework.

### Issues encountered
After the framework upgrade and the additional module update tests were running and all the UniTask coroutine tests have been converted to async Tasks.
The problems arose when the visual tests started running, it appears that the lighting used when running tests in editor vs running tests in batch mode is different.
Additionally the whole system of dividing in two separate folders the edit and play tests changed and requires many changes. Basically now all tests can be in the same files and the playmode ones require a new tag.
Another issue was that some tests were failing randomly at some executions without any apparent reason.
Also even if tests were launched in batch mode from the terminal, towards the end a game window appears running the final tests.

The issue and PR will be closed for the moment and the topic will be re discussed once a stable test framework version is released.
