### ISSUE TITLE
Some Materials show a flickering displaying error

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#243]
Some users have reported graphic error with some flickering materials

May be related to Apple M1:

Hardware Overview:
  Model Name:    MacBook Air
  Model Identifier:    MacBookAir10,1
  Chip:    Apple M1
  Total Number of Cores:    8 (4 performance and 4 efficiency)
  Memory:    8 GB
  System Firmware Version:    6723.61.3
  Serial Number (system):    FVFDTB0TQ6L4
  Hardware UUID:    35D65F7B-EDFF-5D0D-AA62-22B06739FD02
  Provisioning UDID:    00008103-0009511A3462001E
  Activation Lock Status:    Enabled
Google Chrome is up to date
Version 89.0.4389.114 (Official Build) (arm64)

Evidence: 

https://www.youtube.com/watch?v=y4cp2nld8X0&ab_channel=wmike

https://drive.google.com/file/d/1L0VMdfGXg6vrNcr-5z9_bwm0yEVjU2Oe/view

Thread link:

https://app.slack.com/client/T9EJMTT7Z/GV18MQB19/thread/GV18MQB19-1617720314.251200

**Comment by pmacom** [comment]
Adding this thread for reference as well. I wonder if it's happening now due to an extremely shrunk down UV map on an atlas. This happens on every single road instance, which looks terrible for anyone on an M1 Mac. Is there an instance of this parcel that I can pull down and test out on my local machine? I really want to help fix this. It makes the dcl experience kind of bad. I love dcl, so I can ignore it. But I have to explain the issue to everyone when I show them the world. I do a lot of screen shares.
https://discord.com/channels/417796904760639509/500732694100181002/839735288179589120

**Comment by olavra** [comment]
there is another bug that may be related to this issue. We will try to fix this first and them see if solves the other situation. Otherwise we will need a M1 Apple machine to debug.

Steps to reproduce: 
- [ ] Go to  -2,  -11 https://play.decentraland.org/?position=-2%2C-11&realm=unicorn-blue
-

https://user-images.githubusercontent.com/41490935/123647065-0f2f9480-d828-11eb-9059-9236593b6a2f.mp4
