### ISSUE TITLE
Fix emotes panel crash

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2465]
A user reported a way of crashing the explorer by doing quickly:
1. Open the Emotes Wheel with B
2. Quickly press E to open the emotes panel
3. Quickly click in any emote before it finished loading (or in several emotes)

https://user-images.githubusercontent.com/1031741/173486377-1577aadf-89ba-4000-9cf9-c26a732c3568.mp4

For the user that was enough to crash the client, in our case we've observed a freeze of several seconds and huge amount of console errors but without crashing, more than 100 or 200 of this error appear (error too long to be added as text):
[console-error-AddWearablesToCatalog.txt](https://github.com/decentraland/unity-renderer/files/8896104/console-error-AddWearablesToCatalog.txt)

### Acceptance Criteria
- [ ] The client doesn't freeze/crash when following the preoduction steps and the observed console error doesn't appear.

**Comment by dalkia** [comment]
The hiccup is the result of a big error log on the console, that is triggered due to catching an `OperationCanceledException` when kernel asks for an update at the `CharacterPreviewController.cs`.

Its currently in talks with SDK to filter or remove this logging.

**Comment by aixaCode** [comment]
@dalkia There has been [change](https://github.com/decentraland/kernel/pull/400) in the kernel to not include the payload in the error logging. That should lower significantly the amount of logging.

**Comment by dalkia** [comment]
Fixed by @lorux0 in this [commit](https://github.com/decentraland/unity-renderer/commit/9b4d7d6dd4a001f0606b5ff2f549191fa60e6643). 

The Avatar update is delayed one frame after kernel makes the call. This allows to group together all the calls to AvatarUpdate in just one update, and also decouples the Cancellation error from the Kernel call. Therefore, no error is logged in this flow.

The only "downside" is that no CancellationToken error is logged; but its probably not necessary to know if a cancellation was invoked in a build.
