### ISSUE TITLE
spike: Download Handlers allocate a lot of memory

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2481]
`DownloadHandlers` copy a lot of data every time we have to use them, unity provides an allocation free getter that returns a `NativeArray` in Unity 2021+, we might want to use some MemoryStream pools to avoid allocating every time we get the data, so we can safely copy NativeArray data to our pre-allocated array.

We need to investigate if the improvement is going to be worth the effort of this change.

**Comment by mikhail-dcl** [comment]
For Asset Bundles, it's irrelevant as `data` can't be accessed directly and only one copy per URL can exist.

**Comment by mikhail-dcl** [comment]
### Conclusions

- It is possible to use a non-allocating `Stream` created from the `NativeData` of `DownloadHandlerBuffer` in the following manner:
```
public class DownloadHandlerBufferStream : UnmanagedMemoryStream
    {
        private UnityWebRequest webRequest;

        public unsafe DownloadHandlerBufferStream(UnityWebRequest webRequest)
            : base((byte*) webRequest.downloadHandler.nativeData.GetUnsafeReadOnlyPtr(), webRequest.downloadHandler.nativeData.Length)
        {
            this.webRequest = webRequest;
        }

        protected override void Dispose(bool disposing)
        {
            if (webRequest == null)
                return;

            // When `webRequest` is disposed the pointer is no longer usable
            webRequest.Dispose();
            webRequest = null;
            base.Dispose(disposing);
        }
    }
```
Pay attention that we need to keep a reference to `UnityWebRequest` until the `Stream` is disposed. If `UntiyWebRequest` is disposed by `GC` or manually before, the native content gets invalidated and bytes get incorrect.
- GLTF Texture Creation flow:
`WebRequest` is created and cached in 
```
async UniTask ConstructImageBuffer(GLTFTexture texture, int textureIndex, bool linear, CancellationToken token)
```
it calls the "generic" implementation of `LoadStream`:
```
await _loader.LoadStream(image.Uri, token);
```
and then the `Stream` is cached:
```
_assetCache.ImageStreamCache[sourceId] = _loader.LoadedStream;
```
Then it is used like this (the method was modified for clarity):
```
protected virtual async UniTask ConstructUnityTexture(TextureCreationSettings settings, Stream stream, int imageCacheIndex)
        {
            if (stream == null)
                return;

            if (stream is MemoryStream ms)
            {
                using var memoryStream = ms;
                ConstructUnityTexture(settings, memoryStream.ToArray(), imageCacheIndex);
            }

            else if (stream is FileStream fileStream)
            {
                using MemoryStream memoryStream = new MemoryStream();
                await fileStream.CopyToAsync(memoryStream);
                ConstructUnityTexture(settings, memoryStream.ToArray(), imageCacheIndex);
            }
            else
                throw new NotSupportedException(nameof(Stream));
        }
```
`MemoryStream.ToArray()` allocates a new array according to the documentation:
>This method returns a copy of the contents of the MemoryStream as a byte array. If the current instance was constructed on a provided byte array, a copy of the section of the array to which this instance has access is returned. See the MemoryStream constructor for details.
Moreover, this logic should be agnostic to the implementation of `Stream` according to the Liskov principle. 

`ConstructUnityTexture` uses `LoadImage` (that accepts `byte[]`) to convert any supported texture format to the texture.
It is incorrect and leads to unnecessary allocations.
In order to mitigate it the flow should be modified:

1. Instead of using the "generic" implementation of `LoadStream` for loading a texture `DownloadHandlerTexture` should be used: it is the only way I found to download a texture using native data. There is no method to accept `NativeArray` and make proper conversions, the closest one `LoadRawTextureData` just interprets the given bytes (the texture should be created in a proper format beforehand). So this line
```
await _loader.LoadStream(image.Uri, token);
```
should be changed.
2. The flow for downloading from file should be unified as it is possible to load via the same `WebRequest` and have no branch:
```
else if (stream is FileStream fileStream)
            {
                using MemoryStream memoryStream = new MemoryStream();
                await fileStream.CopyToAsync(memoryStream);
                ConstructUnityTexture(settings, memoryStream.ToArray(), imageCacheIndex);
            }
```
3. Thus, `ConstructUnityTexture` will be no longer needed in its current form as it will be handled by `DownloadHandler`, consider deleting the following lines:
```
Texture2D texture = new Texture2D(0, 0, TextureFormat.ARGB32, settings.generateMipmaps, settings.linear);

            //  NOTE: the second parameter of LoadImage() marks non-readable, but we can't mark it until after we call Apply()
            texture.LoadImage(buffer, false);
```
Review the necessity of having:
```
texture.wrapMode = settings.wrapMode;
texture.filterMode = settings.filterMode;
texture.Apply(settings.generateMipmaps, settings.uploadToGpu);
```

**Comment by mikhail-dcl** [comment]
As a result of the spike #4043 is created!
