### ISSUE TITLE
Several scenes not loading in the vicinity of the Tru x Energy studio

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2928]
**Description:**
Several scenes located outside of the Tru x Energy studio are not loading. The scenes in question are all located inside of a square area with the following angle coordinates: 24,-118; 24,-110; 33,-110; 33,-118.
The specific examples for the aforementioned scenes area: 27,-115; 27,-118; 28,-117; 28,-115, 28,-113; 25,-116; 32,-115.

**Steps to reproduce:**

1. Load into the game as a guest or via a wallet.
2. Reach the Tru x Energy studio (26,-118)
3. Walk outside of the studio.
4. Observe the issue.

**Results:**
Several scenes near the Tru x Energy studio are not loading.

**Expected results:**
All of the scenes are loaded correctly.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/d6937d3b-224f-4152-9676-991ec8751a9b/_2928.mp4.

- Platforms: Windows Desktop Client, Web Client.

**Comment by pravusjif** [comment]
A quick dump of the scenes current locked state shows that they never receive the initialization messages from kernel.

Previously we observed this behaviour with scenes whose don't compile and are deployed nonetheless.
<img width="1089" alt="Screen Shot 2022-08-26 at 13 23 18" src="https://user-images.githubusercontent.com/1031741/186949901-e6c141ae-4c12-4416-8b4e-c23d2281d778.png">

I gathered these scene as some of the affected scenes IDs (link to their mappings file):
- [QmeNymPaBrZ5dBQRRunWQ1SuuozmQ3DmLYcWu2tw6NpGaG](https://peer.decentraland.org/content/entities/scene/?id=QmeNymPaBrZ5dBQRRunWQ1SuuozmQ3DmLYcWu2tw6NpGaG)
- [QmZifuXKBih9rcXfmuxRTNFxRWwdTPj8wq7n7WGHGayfkp](https://peer.decentraland.org/content/entities/scene/?id=QmZifuXKBih9rcXfmuxRTNFxRWwdTPj8wq7n7WGHGayfkp)
- [QmU3iJBa78teVgafkd7LxFsSfm43jJJnMYfVVMD1THNcq6](https://peer.decentraland.org/content/entities/scene/?id=QmU3iJBa78teVgafkd7LxFsSfm43jJJnMYfVVMD1THNcq6)
- [QmZYtY9eLwqu7MPdCBHSfc1aTJRL4rxmiqwefNj2UZ5apB](https://peer.decentraland.org/content/entities/scene/?id=QmZYtY9eLwqu7MPdCBHSfc1aTJRL4rxmiqwefNj2UZ5apB)
- [QmZv43RSH3j4hPFw4YiH3jNpm7pXEY4c4LCR7jvoY55ndW](https://peer.decentraland.org/content/entities/scene/?id=QmZv43RSH3j4hPFw4YiH3jNpm7pXEY4c4LCR7jvoY55ndW)
- [QmWFhaFBNrd8vJrJzuks6MBrpj7GFkSVwtCX3Bfnha1tk6](https://peer.decentraland.org/content/entities/scene/?id=QmWFhaFBNrd8vJrJzuks6MBrpj7GFkSVwtCX3Bfnha1tk6)
- [QmcyLbMDFDKSJHdx7p3VF4cesk3WwLTFpK56HtMADzAUuR](https://peer.decentraland.org/content/entities/scene/?id=QmcyLbMDFDKSJHdx7p3VF4cesk3WwLTFpK56HtMADzAUuR)

**Comment by pravusjif** [comment]
I noticed that the scenes that don't load throw the following `_ROTATION_` error in the console:
![Screen Shot 2022-08-26 at 13 33 51](https://user-images.githubusercontent.com/1031741/186955664-dbefa4bd-4d59-4a72-bc65-a6e6f8e0c5f2.png)

By entering the world directly into one of the affected scenes and loading no other scenes (`LOS=0`) we see that only 1 of those errors is thrown per scene: https://play.decentraland.org/?position=27%2C-117&LOS=0

A bit of commit hunting shows that since [this commit in Kernel](https://github.com/decentraland/kernel/commit/6af9c3b0382a2a51446590a1457f24a07ddd3060) we start seeing the `_ROTATION_` error in the console and those scenes never finish loading.
**Test link with that kernel version:** https://play.decentraland.org/?position=27%2C-117&realm=dg&kernel-version=1.0.0-2505075507.commit-6af9c3b&LOS=0

Before that commit (e.g. from [this one](https://github.com/decentraland/kernel/commit/0dd1ae603a3c90b5323dd657a1bc27de02624c84) and older ones) even though the scene is completely broken, it finishes loading.
**Test link with that kernel version:** https://play.decentraland.org/?position=27%2C-117&realm=dg&kernel-version=1.0.0-2503059035.commit-0dd1ae6&LOS=0

**Comment by pravusjif** [comment]
I'm closign this issue since @leanmendoza implemented [a fix](https://github.com/decentraland/kernel/pull/459) to initialize scenes with compilation errors to avoid having their world blockers messing up the world, and the problem around that reported scene has been mitigated.
