### ISSUE TITLE
Multiple hover hints per item

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#2978]
The new SDK7 allows to set multiple button events to a single entity. A single clickable object can have one reaction when pressing E, another when pressing F, etc. How would the hover hints look in that case?

Also, we should think about abstracting the actual key from the input. For example to support in the future remapping the keyboard or using a VR controller.

**Comment by RominaMarchetti** [comment]
I would like to go for a radial layout as proposed [here](https://www.figma.com/file/WVlRA0PztA7RO91hllFx91/Multiple-events?node-id=0%3A1).
https://images.zenhubusercontent.com/337227404/2f1c7012-d8fb-4084-afcd-2b98cb6a5861/screen_recording_2022_09_13_at_22_02_55.mov

Regarding the remap of the keys: the idea is to have a prepared set of icons for all the supported devices inputs in order to be able to show a graphic reference in each hint apart the text.

**Comment by aixaCode** [comment]
Closing, not part of the scope
