### ISSUE TITLE
Improve Bot Instantiation Tools

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#298]
https://docs.google.com/document/d/1Acc5yWt_Q_2Zc-jNkGm_W7mBRILnXBtKm6_GjXlwHLs/edit#heading=h.x4emwpf9ls3q

Use kernel only as an entrypoint and implement solution unity-client-side.

- [x] ~Update Kernel's bot tool with the needed functionalities~
- [x] Remove Kernel's old bot tool
- [x] Implement Kernel entrypoint (we can trigger the tool through our exposed `clientDebug` object)
- [x] Implement bots positional instantiation in unity
- [x] Implement bots area position randomization
- [x] Implement bots wearable randomization ~(use all existent wearable collections)~
- [x] Refactor wearable collections fetching to use safer API: [fetching collections list](https://peer.decentraland.org/lambdas/collections) +  [fetching wearables from randomized collections](https://peer.decentraland.org/lambdas/collections/wearables?collectionId=urn:decentraland:ethereum:collections-v1:3lau_basics&collectionId=urn:decentraland:ethereum:collections-v1:atari_launch)
- [x] Implement position and area default values based on the player when they are not provided
- [x] Implement bot removal methods
- [x] Implement tests or add issue for the future
- [ ] (optional?) Be able to force a master randomization seed (affecting random positions and wearables) to test more deterministically

**Comment by menduz** [comment]
I left a comment in the document, to better implement the stress tests directly in unity and C# and exposing them in the same fashion as the performance meter tool, instead of mocking comms.

Mainly to decouple technologies and components, also to leverage speed of C# and the development pipeline of unity, without needing to touch kernel for that.

Cases of bottlenecks would be also easier to solve, since the stress test initiated from comms could have bottlenecks in the serialization, or message dispatching and queuing. It would be nice to isolate those concerns.

**Comment by pravusjif** [comment]
Cool, I'll use Kernel as an entrypoint and move the implementation to Unity Client then
