### ISSUE TITLE
Add generic Metrics flow to send data through segment

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#299]
In order to add any metrics for the explorer, to measure the users activity, we want to create a generic channel that allows us to send any data flag with any data structure to segment.

This will allow us to create panels in metabase or graphana, and have insights about the performance and adoption of features.

Please agree this feature with Pablo Seibelt

ie: For the Quests project, we want to start measuring when a player progresses on a quest, so relevant data will be:

flag: user_quest_progress

data:
- user_id
- quest_id
- task_id
- progress amount
- taks_status
- timestamp

**Comment by kuruk-mm** [comment]
I suggest to add a `custom metric`.

We can call it in Unity with:

`DCL.Interface.WebInterface.CustomMetric(metricName, jsonData);`

And then to send to Segment we call it like:
`track("custom {metricName}", jsonData)`

So for example you can use:

```
[Serializable]
public class QuestProgressPayload
{
	public int user_id = 0;
	public int quest_id = 0;
	public int task_id = 0;
	public int progress_amount = 0;
	public int taks_status = 0;
	public long timestamp = 0;
}

[...]

QuestProgressPayload payload = new QuestProgressPayload
{
	user_id = 1,
	quest_id = 2,
	task_id = 5,
	progress_amount = 50,
	taks_status = 1,
	timestamp = 123123123
};
DCL.Interface.WebInterface.CustomMetric("user_quest_progress", payload);
```

and we will receive something like this in segment:

```
eventName -> "custom user_quest_progress"

payload:
{
	user_id: 1
	quest_id: 2
	task_id: 5
	progress_amount: 50
	taks_status: 1
	timestamp: 123123123
	sessionId: "27ad6e01-9150-40e8-a6ef-aac81cbbd46d"
	time: "2021-05-06T02:20:54.384Z"
	version: "70e47eeade1720a903b33f60cf48e9f912279016"
}
```

Let me know if we want something like this :)

**Comment by sicarul** [comment]
I think the idea is great, but i would remove the "Custom" name from it, it'll make all metrics read as "custom ..." instead of just the metric. In your example, i'd make it so the name reads:

eventName -> "user_quest_progress"

The rest seems good. The event was just an example, if not, what's that user id? (We already get automatically the wallet if they have it in the current tracking on kernel), also, those quest ids and task ids, will we be able to get them somewhere to give more context rather than numbers? (Also please change taks_status to tasks_status)

Thanks!
