### ISSUE TITLE
Spike: Shader transition investigation

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#3119]
We want to drop the use of the `MaterialTransitionController.cs` and replace it with a shader. The objective of this spike is to analyze if its possible to create a transition effect using just shaders.

The MTC is a script that could be added to a Shape to generate a transition; this involved creating new transition materials which get destroyed at the end of the lifecycle. This was not optimal and lead to memory leaks in different corner cases.

We want to see if its possible to add the effect to the default material in DCL; and using just a function call that access that material to create the effect without the need of adding, removing or destroying anything. 

As a reference, here is the effect using the MTC on every object that appears: 
https://play.decentraland.zone/?renderer-branch=feat%2Fmtc-on-base-shape&realm=baldr&position=-12%2C0&island=Inwcf

In the absence of the Technical Artist the output of this spike will be:
- [x] Remove the transition effect
- [ ] Create a separate ticket for creating a new one

**Comment by MichaelBitsakis** [comment]
Reference / Effect Proposal from Alvaro Luque

https://twitter.com/lateasusual_/status/1575955053315526656

**Comment by MichaelBitsakis** [comment]
Dissolve effect base (on my free time so i can get more time on the high priority issues)

https://images.zenhubusercontent.com/337227404/e1ee1522-659e-483d-b9fb-6be93f4c34ad/dissolve_effect_base_1.m4v

**Comment by xavi-dcl** [comment]
Why do we want this?
1. Performance improvement
2. Better visualsmaking creators life easier, all of the above?

**Comment by MichaelBitsakis** [comment]
This is a transition / dissolve effect. When asset bundles get imported in runtime , they bring the world game objects (items , props , architecture etc) with them. 

Idea is to have a dissolve effect to show up first instead of just bringing up the models in an "off / on" state.

Better visuals is the answer to your question.

**Comment by dalkia** [comment]
+1 to @MichaelBitsakis answer. 

The current disolve effect is called MaterialTransitionController.cs; we want to remove it since it has a couple of issues:

1) Its strongly coupled with the current Scenes Bound Checker. As we are planning on removing the SBC for a new shader based soultion, its going to be hard to readd this componenet.
2) Its strongly coupled with the GLTF importer. 
3) It can only be seen when using GLTF.

Solving this issues will bring using a new disolve effect through a shader wil bring us a cleaner code.

**Comment by MichaelBitsakis** [comment]
New reference fr the effect has been added b @olavra 

https://twitter.com/unitygames/status/1595099857236025346

**Comment by Kinerius** [comment]
We really need to think this through, here are my thoughts:

- The current implementation for GLTFs right now is completely disabled since we are using GLTFast.
- It should be quite easy to just add the MaterialTransitionController component to the result GameObject, but that's not a good implementation, we need a service to manage the lifetime of the effect and react to the change of state of the renderable.
- We could implement a PostProcess effect that affects the whole scene, to load the world for the first time, it should be quite cheap. 
- We can pool the used Materials to avoid creating and destroying them during runtime.
