### ISSUE TITLE
Character stuck running automatically

### ISSUE THREAD

**Issue by TheAlphaFlyer** [decentraland/unity-renderer#3123]
### What happened?

First load into Decentraland after connecting via Metamusk. My character started running downward towards the camera without any inputs. Not possible to stop.

### Steps to reproduce

- Install application
- Set up account
- Load in

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 9 5950X 16-Core Processor 

### GPU

NVIDIA GeForce RTX 3090 24348MB

### RAM

32677MB

### Kernel Version

1.0.0-3127331658.commit-879a231

### Unity Version

desktop-1.0.614-20220923172652.commit-85e7e67

### Realm

artemis

### NameTag

TheAlphaFlyer#16db

**Comment by JorgeDecentraland** [comment]
@kwspgoliasz could you try to reproduce this issue and add any relevant information you can find, please?

**Comment by kwspgoliasz** [comment]
@JorgeDecentraland The issue could not be reproduced on our side. After seeking advice from @Antivortex, it turned out that this issue seems to be analogous to the problem which occurred on the Web client in the past. The fix for that issue was not implemented to the Windows client yet, but Antivortex said that he will take care of it.
