### ISSUE TITLE
Video playing in the internet explorer client but not the desktop client

### ISSUE THREAD

**Issue by iillee** [decentraland/unity-renderer#3217]
### What happened?

I have a scene deployed to 13,90 that uses a webm video file as a material for water. The file plays fine in the SDK and in the internet client but shows as grey in the desktop client. I have tried both streaming the video file via vimeo and including it in the scene. I have tried using both webm and mp4 files. See attached video for issue.

[Uploading desktop client video play error.webm…]()

### Steps to reproduce

Visit 13,90 in the internet client and the desktop client. Compare

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

### GPU

NVIDIA GeForce RTX 2060 5980MB

### RAM

16245MB

### Kernel Version

1.0.0-3206079709.commit-bc57f89

### Unity Version

desktop-1.0.641-20221006152813.commit-5f8ac22

### Realm

hephaestus

### NameTag

ile

**Comment by JorgeDecentraland** [comment]
Known issue. Will be fixed when solving this [one](https://github.com/decentraland/unity-renderer/issues/2995).

**Comment by othmanekhadri** [comment]
Hello iillee, I hope you're fine. I am contacting you via the comment section because I couldn't find another way haha. 
I am part of a French start-up that provides plug and play solutions for web 2 companies directly on Decentraland.
Here are a few links of what we do :
https://play.decentraland.org/?position=-20%2C-133&realm=baldr&island=I74f8
https://www.youtube.com/watch?v=SCez4aOb2YE
https://www.youtube.com/watch?v=bZAKiUfW9QU
https://youtube.com/channel/UC6FBppNmeGtAS3nf9LGHVsQ?utm_source=EKLEiJECCKjOmKnC5IiRIQ
If you're available I would really appreciate to have a little chat with you, we're looking for a freelancer to collaborate with as we integrate more and more features to our experiences.
You can drop me a line at this email address: hiring.decentralanddeveloper@gmail.com
Ps: It's me who wrote a comment on your latest youtube video ^^.
