### ISSUE TITLE
spike: renderer crashed on launch or is started in software emulation mode on web

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#3218]
We discovered a condition in MacOS web that makes the renderer start in "Software emulation" mode. which is not only the slowest experience you can get, it is also not precise.
From time to time, the reason is also not yet defined, renderer will crash and not start properly.

From user perspective, the DCL is stuck on loading screen

Currently we have new exception added to rollback to track the scope of the issue
https://rollbar.com/decentraland/World/items/71353/
![Screen Shot 2022-10-10 at 14.35.20.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/7f6958aa-df79-4295-b5a1-1f7bbc33053c)

Attaching screenshots from the debugging thread:
![Screen Shot 2022-10-10 at 09.57.08.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/03e3eeb3-f08c-4723-a1e2-9cd1524fd684)

More info on slack thread:
https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1665401220894309

**Comment by Kinerius** [comment]
I had this happen to me today. 

Something I've noticed is that I had a graphics blackout because my graphics driver was updated or for some reason it crashed and reloaded, after that, I couldn't run properly the Decentraland renderer on WebGL and it was throwing this exact error.

It was fixed after closing and re-opening chrome.
