### ISSUE TITLE
Avatars appearing as floating off the ground after spawning in various locations

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3397]
Description: 
In various scenes avatars of other users appear as floating off the ground. Floating occurs for avatars that are located in a spawn location for a given scene. Issue is most pronounced in the Genesis Plaza spawn area.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Use the `/goto 0,0` command to teleport to Genesis Plaza's spawn location.
3. Observe the avatars of other users.

Results:    
Avatars appear floating off the ground.

Expected results: 
Avatars appear standing at ground level.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshots for reference.
![floating1.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/060212a2-6d97-4740-84a4-befa2de4a7e3)
![floating3.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/9e194f26-8490-4bfb-81b8-64005410ece4)
![floating2.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/d9fd56fd-2fc9-4291-9d46-b69d47bfb632)

**Comment by dalkia** [comment]
The issue is ocurring because, after ADR-81, the peer avatar is set as visible before the loading screen (and physics) are completed in renderer.
If during the loading focus of the app is lost, the position is never updated.

After disussing it with SDK team, the plan is to mitigate it by changing the spawn point in Genisis Plaza so its directly on the floor, and not in the flying position.
Next step is going to be coordinate with comms the implementation of an "idle" state. If an avatar is idle, it wont be shown. Idle state will finish when loading finishes their lifecycle.
The issue is going to be created by the SDK team.
