### ISSUE TITLE
Scene assets are not always loaded when jumping to specific locations

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3411]
branch for culling controller #3912 

Description:
When loading between locations not all local assets are correctly loaded.

Reproduction steps
- Clear cache
- Switch between different locations and/or jump between local friends
- Notice loading screen can often disappear before all local assets are fully loaded.

Expected results:
Local area assets are loaded before the loading screen is closed.

Notes:
This could again be related to SDK team / message ordering and also potentially be related to #3409 

Platforms
Web Client, Windows Client, MacOS Client.

**Comment by Kinerius** [comment]
I was thinking about this and we might want to try and tweak the culling throttling when loading stuff for the first time, maybe it is way too slow. Especially with big scenes with multiple parcels, they go from invisible to visible way too slowly without giving priority to the closest renderers.

**Comment by xavi-dcl** [comment]
Interesting comment @Kinerius, I guess such tweaks need careful testing/validation, but have the potential to improve the user experience a lot.

Loading screen disappearing before local scene is fully loaded is something that already annoyed me 2 years ago. As far as I remember, there was a timeout so you may end up entering the world even if the loading did not finish. Not sure this is still the case, and if that behavior is desirable. IMO at least the actual parcel you teleport to should be 100% loaded otherwise it is a really bad experience and can break the content (I remember being able to access parts of scenes that I was not supposed to enter because colliders were not yet loaded). Again, this was probably fixed long ago.

**Comment by m3taphysics** [comment]
Lets wait for SDK7 and protobuf to see if an improved message system fixes this issue

**Comment by PalauiDCL** [comment]
Added a restart to the culling system and an event that is called once a full culling cycle completes
