### ISSUE TITLE
Add Friend button takes forever to react

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3457]
When clicking on a friend request button, either on the context menu or the passport, the buttons do not react at all, until they change to "Invite sent". It feels like its broken, and I try to click again and again.

**Acceptance Criteria**
- Button should provide feedback to player when its clicked
- While its running, it should not allow players to click again
- Make use of some sort of wording or spinner

**Comment by RominaMarchetti** [comment]
Show the spinner in all the stages of the button while a request is running and replace the color of the container and text to make it look blocked, because on its loading stage it's not interactable.
![Screenshot 2022-11-14 at 14.23.24.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/d95c6c0c-a599-4029-8b79-e173f6efa41d)

[Figma file](https://www.figma.com/file/HEjNjFOQUcCgLK3lDMFrw5/DCL-Design-System-%26-Guidelines?node-id=1936%3A1549)
