### ISSUE TITLE
NFTs saying "Not for sale" 

### ISSUE THREAD

**Issue by NotBitcoinCEO** [decentraland/unity-renderer#3509]
### What happened?

Wondering why NFTs say they are "Not for sale" after clicking the thumbnail when they are for sale in two different locations.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/96089214/201454462-04a98a7b-0f96-4350-8595-fe4fca3ff709.png)

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1660 Ti 5991MB

### RAM

16322MB

### Kernel Version

1.0.0-3447314206.commit-3cd6272

### Unity Version

desktop-1.0.768-20221111011819.commit-45e707d

### Realm

artemis

### NameTag

Synth

**Comment by kwspgoliasz** [comment]
The 'Not for Sale' message is also used in situations where the NFT is for sale but has no specified price. In these situations, the users can suggest their own price after accessing the OpenSea website. The dservices team found that there are only two options set for the Price section: 'n ETH' or 'Not for sale'. A 'Not specified' label should be added as the third option in order to address this issue.

**Comment by aixaCode** [comment]
Closing, not part of the scope
