### ISSUE TITLE
Black/grey textures changes to green in a deployed scene

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3607]
The creator claims the problem to the latest updates of sdk `npm i decentraland-ecs@latest`. It doesnt happen if he runs `npm i`.

Repro steps:
1. Go to deployed scene `-8,-69`
2. Try changing the skybox's time to daylight, it may help to detect the issue
3. You should notice that black/grey textures changes to green

![Screenshot_2022-11-25_at_16.52.31.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/01fe78ba-9698-46a1-9f59-84d464abb04b)
![Screenshot_2022-11-25_at_16.50.06.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/b677a808-e789-44c7-a883-614f190b7ee8)
![Screenshot_2022-11-25_at_16.52.16.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/a9f3d1d0-17ea-4dc2-bff6-1a9e678bcf1e)
![Screenshot_2022-11-25_at_16.49.43.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/4f444639-93ef-442c-bee3-d207cc3f126c)

**Comment by 0xD-Fabio** [comment]
I've dug more into this issue, and we found out that it seems to be a model problem:
 Model takes color data from the assigned texture in a specific part of it.
The rest of the model receives no texture/color data, so by adjusting the color of the material, ONLY the part that is receiving data changes color. The rest reflects the environment only based on the smoothness value.
I also went back to older commits, and I found out that the bug was also there with previous Renderer versions.
What made the model-material issue pop out more was the implementation of the Infinite Floor, which blends the skybox color to the world's edges.
In this way, the affected wall material over-reflects the skybox and the floor color and makes this issue more visible.
Hope this helps to fix the problem! :+1:
Please take a look at the video for more context.

**Comment by 0xD-Fabio** [comment]
[Uploading... 2022-11-30 12-21-10.mkv]
