### ISSUE TITLE
Send the user to home or 0,0 after he has been kicked from a world

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#3780]
When a user gets to a world, the creator's coordinate for that world gets embedded in the url. If the user is kicked out fo the world (due to it being full) the coordinate is already embedded in the url and the user gets teleported to that coordinate. We need to find a way to send him back to home or 0,0

### Acceptance criteria

- [ ] When a user gets kicked out of a world, it teleports to home location

**Comment by xavi-dcl** [comment]
Involves Kernel, may need support or assign the task to the Kernel team

**Comment by popuz** [comment]
As from my investigation, I think we can add logic inside of `/scene-loader/sagas.ts` method `unsettlePositionOnSceneLoader` for getting the `lastPosition`. The logic should check if the previous scene was World and new one will be not World, then it should use 0,0 as lastPosition and otherwise go with the current `getParcelPosition`. 

This will not break any logic of Teleporting via /goto chat command or Map teleportation (both used from the World)

**Comment by popuz** [comment]
Due to my basic TypeScript knowledge, I wasn't able to track who calls `unsettlePositionOnSceneLoader` and when. As well, I have no any idea how we can provide there information about that previous scene was world and new one will not be a world
