### ISSUE TITLE
Issue with parcel highlighting for the Asset Bundles detection

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3783]
**Description:**
Some parcels and objects are not affected by the Asset Bundles detection, resulting in a lack of highlighting for the affected locations. The issue seems to occur mostly, but not exclusively, for empty parcels.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Find an empty parcel or go to one of the following coordinates: **-45,0** or **-82,-107**.
3. Use the /detectabs command in order to turn on the Asset Bundels detection.
4. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
Some parcels and objects are not affected by the Asset Bundles detection.

**Expected results:**
All parcels and objects are highlighted when the detection is turned on.

**Notes:**

- The issue can be reproduced on both the guest and wallet accounts.

- The issue can be reproduced on both the production and development branches.

- Please see the attached screenshots for reference:
![#3783_01.jpg](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/9901caa2-8e8b-4ca3-b5fc-104844eaf2ae)
![#3783_02.jpg](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/7cf134c5-dc76-40b4-9f48-d3303e7607ea)

- Platforms: Web client, Windows client.

**Comment by PalauiDCL** [comment]
I think I have detected the problem, in fact there ate two of them:
- For the first picture in the issue definition, the problem is that the scene transforms do not have a tag, see the picture.
![image](https://user-images.githubusercontent.com/113350816/208374560-11aea301-7e44-4bd4-8520-218069129244.png)

- For the second picture in the issue definition, the scene is not showing to the player, the renderers are detected but, as they are not shown, there is nothing to show.


The solutions for both this issues seem to be outside of the Asset Bundles detection tool. I request this thought as a post-daily.

**Comment by PalauiDCL** [comment]
@m3taphysics Asking for space for explaining about this issue, maybe in a post daily to check if my assumptions are correct

**Comment by eordano** [comment]
What is the status of this @PalauiDCL ?

**Comment by PalauiDCL** [comment]
@eordano Working on it, the hypothesis is that this issue is not related to the AB detection tool, but I am investigating through it if I can find the error that is provoking this behaviour.
Currently it seems a specific issue of how the scene was exported, looking through the asset bundles loading data to find it currently

**Comment by PalauiDCL** [comment]
![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/8238a375-a480-413e-bb76-4c4af5ab9778)

Detected and solved.
As expected, the issue had nothing to do with the AB tool, it had to do in the way we implement "ParametrizedShape", in there, we are creating the shape after the loading based on certain parameters, so the assets do not have tags assigned and can not be detected. We should make a decision on how we want to handle this exception, we can consider it an asset bundle and solve it using the existing tag for example (Solution used for the picture).

In the meantime, a bug was discovered in the loading of GLTF Fast, this bug will also be corrected in the PR

**Comment by PalauiDCL** [comment]
![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/b1f16c23-a4df-4953-ad2a-67714accc3c9)
Added for parametrized shapes, ready for PR
