### ISSUE TITLE
Analyze GLTFast performance and decide whether to shift 100% to it

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3873]
Add comment with decision & criteria

**Comment by Kinerius** [comment]
# CPU Usage

### GLTFAST
![image](https://user-images.githubusercontent.com/7646450/211053370-9b5acf9d-b099-4963-9ad9-e6b67845e613.png)

Max: `118,56 ms` MainThread

### Old GLTF
![image](https://user-images.githubusercontent.com/7646450/211053549-e9cc97fe-1eb9-4b9b-bd77-bc069211c726.png)

Max: `214.25 ms` MainThread

## Conclussion
GLTFast is `1.8x` times faster loading the same GLB. 
GLTFast is 3 frames faster.

# Memory Usage

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/3a2fa9df-2345-4ff3-b444-d3fb603d8e3b)

A = Old GLTF
B = Gltfast

The memory usage is the same but the Graphics one is doubled because the 2k texture of the test gltf was not being resized, so the memory usage should be a bit lower.
