### ISSUE TITLE
PoC: "lock cursor only when right-mouse button holds" mode

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3877]
# Description
Leave cursor locking only for "right-click camera movement" (already existing) and remove it from other interactions.

PoC:

- [ ] Add a setting (checkbox, disabled by default) in the backpack/settings UI
- [ ] Prevent locking the mouse always, relying on "right-click camera movement"

AC:
- [ ] Lock the cursor only when user is holding right-mouse button, and release the camera lock when the right-mouse button is released 
- [ ] Disable locking cursor in all other scenarios

**Comment by eordano** [comment]
When double-right-clicking, with a ~50% repro rate, in Firefox over Linux, I get locked in. May be a race condition in the web+unity interaction, but it's pretty annoying. 

I can't reproduce on Chromium over Linux.

**Comment by popuz** [comment]
I think the problem is that default notification popup in Firefox about cursor being controlled by the website, takes the focus and logic about unlocking the cursor is skipped (if performed during this popup show). Possible solutions could be 
https://forum.unity.com/threads/chrome-browser-popups-causes-webgl-app-to-lose-focus-and-cant-be-regained.1223469/
https://forum.unity.com/threads/ui-button-stops-working-permanently-after-switching-tabs-on-mobile-safari.1029688/#post-7828047
