### ISSUE TITLE
Show all messages in the notifications area

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3955]
After sometime working with the channels + private conversations + nearby, I really need to admit that the notification area feels like random information. I would like to try to show all messages received from the channels I want to get notified, independently if I'm currently viewing a particular channel.

Have this behind a feature flag, to try it first.

**Acceptance Criteria**
- [ ] Display ALL messages from all my conversations that have the notifications enabled in the notification area

**Comment by lorux0** [comment]
@olavra it also includes the SYSTEM notifications?

**Comment by RominaMarchetti** [comment]
@lorux0 replace the title `Private message` for `Direct message`, and add next to it the name of the player who I'm talking to. 
Received messages from that DM shows the pic and name of my friend. Sent messages don't show my pic and instead of showing my name it says `You`
![Screenshot 2023-02-02 at 09.47.38.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/64a9ef91-d3ae-421b-bb6b-6cd9bd7a8596)
