### ISSUE TITLE
Address technical debt introduced in new passport feature

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#3961]
TDB After meeting with tech leads

**Comment by AjimenezDCL** [comment]
Since github wont let me do a code review with a PR. Here it goes some of the stuff I've seen:

## NFT Icons 
- What's the point of extracting `INFTIconComponentView` if it's never going to be used?

NFTIconComponentView
- the event wrappers to `marketplaceButton` and `detailInfoButton` are error prone due to the null conditional operator.
- `if (nftItemInfo == null || (nftItemInfo != null && !nftItemInfo.gameObject.activeSelf)) => if (nftItemInfo == null || !nftItemInfo.gameObject.activeSelf)`

NftPageView
- avoid all the boilerplate unsubscription to `nftElement` wrapping it in a configuration/register method.
- `nftIds` doesnt need to be initialized to an array of 4, it's wasted memory allocation.

## Passport
Why do we need to go through the uber-legacy HUDController? The plugin could instantiate the controller itself (provide all the references), avoid the DataStore `enableNewPassport` and everything else related to the old HUDController.

PlayerPassportHUDController
- Should be in charge of changing any global context such as `CommonScriptableObjects.playerInfoCardVisibleState.Set(visible)`, that's not the View's responsibility.
- All the async method should have cancellation tokens and the class should have a lifecycle cancellation token for when disposing (use linked cancellation tokens).
- `QueryNftCollectionsAsync` can make both nft collection requests in parallel.
- Extract constants in `ClickedBuyNft` maybe put them in a common place if needed
- We can wrap all the stuff related to preparing the data for `WebInterface` in the passportAPIBridge. We'd reduce coupling and is also going to be closer to the future implementation with a kernel service.

PlayerPassportHUDView
- The relationship between controllers and views for subpanels is strange. Currently PlayerPassportHUDController has references to the Info/Preview/Navigation controllers, and the PlayerPassportHUDView to the corresponding views, it seems super weird, ideally only a controller should have knowledge of its view. Evaluate a design where only `PlayerPassportHUDController` has a reference to the other controllers and remove references to views in `PlayerPassportHUDView`.
- Avoid global accessors like `MouseCatcher` or `CommonScriptableObjects.playerInfoCardVisibleState`, they can be provided as a params in `Initialize`.
- `animationCancellationToken` needs to be disposed to avoid leaks.

**Comment by AjimenezDCL** [comment]
More review!

## NFT Icons (round 2!)
- `NFTIconComponentModel.type` and `NFTIconComponentModel.rarity` might be better as Enums; otherwise it's prone to human mistakes. If not doable, at least wrap them into constant literals instead of hardcoding them.

## Passport Navigation

PassportNavigationComponentController:
- LoadAndShowOwnedWearables is prone to race conditions. The current promise is not forgotten.
- LoadAndShowOwnedEmotes has the same issue.
- LoadAndShowOwnedNamesAsync needs cancellation
- LoadAndShowOwnedLandsAsync needs cancellation

PassportNavitagionComponentView
- CreateNamePageElements, is `nftIds` actually needed? Also we should extract `4` as a constant.
- CreateNamePageElements, as mentioned before, avoid literals for `type` and `rarity`.
-  CreateEmotePageView, same as before about literals and extract `4` as a constant. Also nftIds could be cached to avoid allocating memory every time this method is created.
- CreateLandPageView, same as before about literals, constant extraction and cache of nftIds to avoid allocation.

**Comment by AjimenezDCL** [comment]
## PasportPlayerInfoComponentController
- UpdateWithUserProfile whole flow needs to be refactored to accept cancellation tokens instead of attaching an external one. You need FriendsController compatible with this to complete this request.
- CancelFriendRequestAsync should have, at least, have a disposing CT. To avoid cases like shutting down the application while this keeps performing something in the background.

Note: Since we are not listening to changes in the `profanityChatFilteringEnabled`, the content wont be updated if we disable/enable the profanity filter

## PassportPlayerInfoComponentView
- SetName can avoid `Contains` and directly split by #. First element always will be the name, the second one might be optional.
- ForceRebuildLayoutImmediate is super slow, this should be used only as a last resort mechanism. Evaluate alternatives or add a comment with the usage reasons.
- Replace Coroutines by Tasks
