### ISSUE TITLE
Test & Enable WebGL Asset Bundles on Desktop

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4069]
## Context

We already have Asset Bundles converted for WebGL, they may also work on desktop and we can get a huge win by seeing if a simple code change to load them will benefit us.

If this does not work we need to also add a conversion for Desktop platform to make these assets available in the desktop format.

## Deliverables

- [x] Enable loading of WebGL Asset Bundles on Desktop
- [x] Verify if they load without issue
- [ ] Enable on Desktop (if required)

**Comment by mikhail-dcl** [comment]
I tested Asset Bundles built for WebGL on Standalone and they do not work:

>The AssetBundle XXXX can't be loaded because it was not built with the right version or build target.

It looks like in the Editor there is special compatibility logic to allow loading ABs from other platforms. Besides the confirmation of such behavior, I could not find any additional information.

Neither I could find any way of bypassing such a check, and the closest explanation I could find is something like that: some assets have right the same serialization among different platforms, some do not, and it is a problem to define the common ground, that's why Unity decided to not support cross-platform Asset Bundles at all.
