### ISSUE TITLE
Spike: Create specification for addressable migration

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4074]
## Context
Unity addressables will give us a lot more flexibility with regards to asset management. Plus unitys general direction is moving away from asset bundles so we should look to begin adopting this. The process can be done gradually but it need some thought. See here for reference: https://docs.unity3d.com/Packages/com.unity.addressables@0.8/manual/index.html

**Deliverables**
- [x] RFC describing the process of implementing addressables

**Comment by mikhail-dcl** [comment]
### The information needed in RFC
#### [Profiles Configuration](https://docs.unity3d.com/Packages/com.unity.addressables@1.21/manual/AddressableAssetsProfiles.html)
A profile contains a set of variables used by the Addressables build scripts. These variables define information such as where to save build artifacts and where to load data at runtime.
The default profile is not suitable for our purpose
![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/a218f36c-1d2a-4ec9-a8f7-2268ac3be89d)
It does not contain any URLs to our CDN
We need to provide information on the following topics:
1. Do we need several profiles for Editor, dev and prod environment? For example, we can use "Editor Hosted" for Editor and "Custom" with our own URLs for dev/prod. We may want to provide different URLs for dev and prod.
2. Provide proper URLs to our CDN, considering using individual URLs for Platforms. We may use `[BuildTarget]` to differentiate
3. Do we need to provide additional variables to use them from Catalogs?
4. `Local` section refers to assets in `StreamingAssets` folder. In our current setup these assets will be a part of the npm package. It means that even if they are not changed they will be duplicated every time on the server. We need to decide on if this setup looks proper to us or we need to use CDN in a smarter way.

#### Diagnostics
We may want to enable "Profile Events" for dev builds. It will require some modifications from CI side.

![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/45a16359-65c2-43f7-b94b-f8be3aab39ff)

Consider disabling "Log Runtime Exceptions" as it should be handled by `UniTask.AddressablesExtensions`

#### Catalog and Content Update
In the Addressables workflow, the request first passes through the Catalog system. The system decodes the address into a location, which consists of the data generated during the build about what the asset is, its dependencies, whether it’s local or remote and so on. 

We can use this system to upload the catalog to the remote server automatically.
if we decide to use 'Local' only, we can skip it.

1. If we provide "Player Version Override" we can use a commits-based system instead of timestamp-based
2. We will need to setup
 ![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/27176388-0c04-430c-9c73-a657e11eb974)
properly, [BuildPath] and [LoadPath] are inherited from the current `Profile`. It can be also used if we decide to utilize `Editor Hosting`
3. Then we can store versioned assets under the same URL

If we decide to go with CDN based addressable we will need to set the following properly (similarly to our `UnityWebRequest`-based system)
![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/7bf8e09d-f215-48d9-b527-1c1e1e30860f)

#### Addressables Build
We need to define if we build `Addressables` from the script or just set it in the `Global Settings`:

![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/007889d8-deaa-4a2a-a22e-83140c415af5)
![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/1d99f511-d3ad-41f9-ae30-67f74280c9d3)

It's preferable to do it anyway from `Settings` as we may provide own scripted ways of building here:
![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/3653bc73-df5c-4a1f-b925-805402510848)

Also, we need to define the rules of how we load `Addressables` from the `Editor` to prevent disconvergence between development, testing and prod.

According to my experience it's better to simulate `Addressables` than using directly from `AssetDatabase`. It may help revealing some async flow issues earlier.
![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/69fe0c32-db59-44d9-a096-71a3f8c99a38)

#### [Group Settings](https://docs.unity3d.com/Packages/com.unity.addressables@1.21/manual/GroupSettings.html)

Group settings determine how the assets in a group are treated in content builds. For example, you can specify where AssetBundles are built, bundle compression settings, and so on.

![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/cce286ca-823f-4959-8e1e-acb8cfabef19)

We need to define how we distribute assets in groups:
1. Define how many purposed groups we have: 
   - some of them may refer to `Local` Addressables such as `Fonts`
   - others can go to the remote server according to the `Profile` settings
   - Go carefully through all the advanced options:
      - We may disable `Addresses`/`GUID`/`Labels` if they are not used for referencing making the catalog (that is in `JSON`) much lighter.
      - We don't need to append `hash` to a bundle name for `Local` assets as they are distributed per package anyway

2. Define granularity (the rules for granularity) for groups creating: e.g. all embedded assets such as fonts may go the single group
3. Define the rules of assets referencing: we may use `Address`/`GUID`/`Label` but we probably don't need all of them at once
4. Decide on if we need to load assets from `Resources` by `Addressables` system. If not remove 'Built In Data` from `Profiles`
![image.png](https://images.zenhubusercontent.com/6372468dd92e9345aaf2a108/5fc4e163-5f19-4b28-bb96-14cc9db30bab)
Removing it will free up a lot of entries in `catalog`

**Comment by aixaCode** [comment]
Another thing to consider is bundle grouping and the potential duplication of assets (It's the same problem as with regular asset bundles). Unity provides an analyzer for that to determine those problems.

**Comment by mikhail-dcl** [comment]
https://github.com/decentraland/adr/pull/182

**Comment by m3taphysics** [comment]
Awaiting content writers
