### ISSUE TITLE
Settings not getting saved correctly on WebGL

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4137]
Reproducibility rate on Linux and Windows, Web3 user, with Chromium: 100%

Changes that DO get saved:
* Some "General" options, like the SkyBox time (but not the SkyBox enabled/disabled toggle)
* Everything in the "Audio" tab

Things that are getting lost:
* Most of the "General" options
* Everything in the "Video" tab

**Comment by eordano** [comment]
Firefox, WebGL:

Before refreshing:
![20230126_113942](https://user-images.githubusercontent.com/42750/214864516-9d2de2fe-dd0c-4446-b20c-2e84139634fe.png)

After refreshing:
![20230126_114036](https://user-images.githubusercontent.com/42750/214864568-5265ce43-de1f-4cec-98f3-f5aac44b7a7a.png)

**Comment by kwssbocian** [comment]
On webGL currently the changes in the settings are not being saved immediately when the changes are made. Saving requires closing the ExploreV2 menu. Additionally the functionality of the setting saving itself is having issues as changing various settings then closing the menu and refreshing the tab with WebGL client sometimes results in the settings not being saved as well.
However this is not the case for Desktop. On desktop all settings are saved immediately, but the FPS Limit and V-Sync after restart always end up defaulting to FPS Limit: Max and V-sync: On. On webGL and Desktop Hide UI setting always defaults to On upon restart.



**Case 1:** On WebGL check that various settings in all three categories are saved immediately upon making changes in the Settings menu. Settings should be saved immediately upon changing and not just when exiting the menu or choosing "Logout" option in the profile.
1. Login into the platform with either a guest or a wallet.
2. Open the Settings menu ('P'). Change any of the settings.
3. Close the browser window without first closing the Settings menu.
4. Start the client up again using the same browser and navigate to the Settings menu.
5. Ensure that the state of the settings before restarting has been saved succesfully.


**Case 2:** Check that the settings that have been changed have the same state after restarting the client.
1. Login into the platform with either a guest or a wallet.
2. Open the Settings menu ('P'). Change any of the settings.
3. Close the browser window then restart the client using the same platform and navigate to the Settings menu.
4. Ensure that the state of the settings before restarting has been saved succesfully. 
Additionally on webGL and desktop ensure Hide UI in General and on desktop FPS limit and V-sync have been saved.


**Case 3:** Check that various settings in all three categories are saved when logging out of and in to a wallet or when switching between a wallet and a guest account on the same platform.
1. Login into the platform with a wallet.
2. Open the Settings menu ('P'). Change any of the settings and do not close the settings menu.
3. In the Avatar's profile menu in top right use the Logout option.
4. Log in again using the same wallet. Go to the settings menu and ensure the changes in the settings have been saved.
5. Repeat the process for the guest login but instead of Log Out use the Sign In option that is available in its place.
Ensure the settings are saved when repeating the process through journeys:
- Wallet to wallet
- Wallet to guest
- Guest to wallet

**Comment by eordano** [comment]
Thank you @kwssbocian !

FYI "Hide UI setting" SHOULD be reset upon restart. That's easy to change with a hotkey (U).
