### ISSUE TITLE
Video live streaming not working on windows desktop client

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#4306]
The issue its only happening on Windows desktop client. Works properly on WebGL or Mac.
Video streaming link: https://livepeercdn.com/hls/91c9wuzoj6lc32gb/index.m3u8

Repro steps:
1. Open the desktop client in Windows
2. Go to -1,-34
3. Go to the back of the scene and check that the video is not working property (white rectangles)

![image.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/563f93cd-f55a-4662-a583-8b8bfaa878c7)

Acceptance criteria:

- [ ] the video streaming should work on all platforms, including Windows

It should look like this (played on Mac):
![Screen Shot 2023-02-07 at 13.00.21.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/e519ef4c-bfb4-42ab-a101-a08f3e7e40ed)

**Comment by CheddarQueso787** [comment]
Thank you, please let me know if there is any way I can help. For more reference: The sound from the video stream comes thru perfectly on web, but the video and scene are too laggy for me to be able to create content or even just walk around. I am using DCL client because it is much smoother than web version, everything works to perfection, but there is just this one issue with the video stream, and it's only at Sugar club. In the last couple of days I have been able to see live video streams at Curation Station and Stoney Eye studios without a problem.  


![Screenshot (1244)](https://user-images.githubusercontent.com/103957712/217331381-c8c96c73-e870-46ef-97bc-6e0c2b8f7f64.png)
![Screenshot (1241)](https://user-images.githubusercontent.com/103957712/217331385-c42451ff-62da-40d9-9eb0-41db9a361580.png)

**Comment by toosad** [comment]
hello @lorux0 Sugar Club here, if anyone has an idea how to debug this or what might be causing the issue let us know. i can set up a live stream for testing purposes for the coming days between 3-6pm UTC . with the stream info above. 

We are streaming at 30FPS, resolution 1280/720, 1500 kbps . 

Our screen for lives stream uses the repo code for video projector: https://github.com/decentraland-scenes/uv-projector

**Comment by toosad** [comment]
new test has been done on the scene . (location -4,-35) 
Empty scene deployed with a default live stream screen . no additional assets or code is present.
![image](https://user-images.githubusercontent.com/50675840/218420194-45515c0b-4b61-4a7d-9154-4664aaf921d5.png)
![Screenshot_1270](https://user-images.githubusercontent.com/50675840/218420214-879a829a-5a86-4203-8307-356947a19725.png)

Some users still report the stream not playing on windows client.

**Comment by 0xD-Fabio** [comment]
Using desktop client, I went to the scene to investigate this issue and met CheddarQueso787, who confirmed the video streaming is now working after changing the content server back to the old one.

![sugarsceneVideo.png](https://images.zenhubusercontent.com/633adb3e5510f3d8ef8164d7/fdfe2d25-6bd9-4c28-9596-9029bb696d6d)

**Comment by gtrgit** [comment]
The video screen did not work for me. I am using windows 10

**Comment by CheddarQueso787** [comment]
Maybe @toosad isn't playing a video right at that moment. I would get with him and make sure he is streaming or try tuning in to the live stream this Wednesday at 6pm ET.
