### ISSUE TITLE
Spike: Investigate high end GPU's / large resolutions and why the FPS drops significantly

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4330]
### Description
By default we create the desktop version at full resolution 1.0 scale, even on high end retina displays. The higher end devices should easily support this, we should investigate if any of our specific post-processing effects or other features are causing the slower FPS or if this is just due to a larger resolution. The default settings should be either better configured and/or the source of the problem should be fixed.

**_(if needed)_** We should have an array of settings / feature flags that we can toggle during the experience to allow us to narrow down the issues. **And/or** profile a built-desktop version on the right machines that are having performance problems.

### Early investigation result:
Gaussian blur expensive for 4k resolutions - nerf Outline shader (new issue: XXX) and re-evaluate this card.

### Deliverables
- [ ] Profile the full-screen desktop build, find source of issue
- [ ] Create togglable rendering features to narrow down the issues (post processing, outline, e.t.c) (if needed)
- [ ] Determine why larger resolutions are slow to run
- [ ] Adjust default settings so better suit the performance we can support

**Comment by 0xD-Fabio** [comment]
### Pre-investigation experiment:
Tried stretching the browser on both of my monitors (ultrawide + laptop), and I got some framerate issues.
#### Laptop Specs
Processor	12th Gen Intel(R) Core(TM) i7-12800H   2.40 GHz
Installed RAM	16.0 GB (15.7 GB usable)
GPU			Laptop Rtx 3070ti
Monitor 0:	Laptop screen 2560x1440
Monitor 1:	Ultrawide 3440x1440

Using the normal ultrawide resolution at Ultra, in the browser, I get around 50-60 FPS
![DCLstretchedBrowser1.png](https://images.zenhubusercontent.com/633adb3e5510f3d8ef8164d7/474008d2-f067-4d77-bd7b-5152a49060ff)
This is the with the browser stretched across the monitors
![DCLstretchedBrowser0.png](https://images.zenhubusercontent.com/633adb3e5510f3d8ef8164d7/f7528e12-bbf9-4899-8a92-3dc1f689e793)

**Some observations:**

1. When I close the settings menu I got a noticeable framerate drop, while fading, and it recovers 2-8 FPS when the fade is over
2. The scaling parameter made it crash with ultra ultra wide stretched. So there is definitely something wrong with how the scaling is applied.
3. The wider field of view made the polycount go up a lot.
4. I noticed a drop in framerate while manipulating other applications on the PC, and while opening the screen recorder. That would confirm that we are also somewhat CPU bound. To better test this. But that could also be because Windows 11 uses GPU more intensively

**Comment by m3taphysics** [comment]
![image.png](https://images.zenhubusercontent.com/63566805658b35a37eaf393c/a3e5236f-d12b-4807-b527-6be955419b8a)
