### ISSUE TITLE
Investigate why the FPS in Chrome is much higher than the FPS in the debug menu

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4341]
### Description
The fps we report in the debug menu is much lower than the FPS we report that is shown in chrome. We should investigate our reporting of the FPS to ensure it is accurate. To enable the FPS counter in chrome open up the console with F12 then press Ctrl + Shift + P then type "fps" and hit enter.

### Deliverables
- [ ] Validate & potentially fix the FPS reporting if it is invalid

**Comment by popuz** [comment]
Chrome FPS Metter probably uses `requestAnimationFrame()` to make its calculation. My tests showed that Chrome FPS Metter gives over-estimated FPS. For example, in Ice Poker scene it gives 10 frames more than Unity calculation:
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/c3983dfe-62f0-4e87-a20d-65ae136e2771)  

However, similar [FPS tool](https://github.com/ArchiTecTor/browser-plugins/tree/master/fps_meter) for Firefox is very near to Unity measures:![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/d6a6c696-98f2-4ebe-b8cf-ccef28b1a945)

**Comment by popuz** [comment]
However, in our code base we calculate `FPS` and `ms` differently and that is strange, because they should be connected via simple equation `FPS = 1000/ms`. However, the deviation is not that big - in the following example FPS calculated from ms would be ~21.3, while our custom calculation shows 19
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/e6e813e7-dce4-4a2d-a301-298b0cf6b1e2)
