### ISSUE TITLE
[Timebox] Review default settings and increase FPS by lowering/disabling effects

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4342]
The setting presets ("medium", "high", "ultra", etc...) were calibrated when the build was still being done on Unity 2021. We should review the effect it has on different machines and recallibrate it.

**Comment by popuz** [comment]
I would propose these changes:
### LOW:
- disable Ambient Occlusion
- disable Additional Lights
### MEDIUM:
- drop resolution to Normal instead of Match Screen
- drop rendering scale to 0.9
- change Ambient Occlusion from Medium to Low
### HIGH:
- drop resolution to Normal instead of Match Screen
- set Anti-Aliasing to 2 instead of 4
### ULTRA:
- drop resolution to Normal instead of Match Screen

**Comment by popuz** [comment]
in general, I would not set Resolution == Match Screen for any preset. For example, I can easily run our **ULTRA** settings in my PC with Normal resolution, but when Resolution set to Match Screen (which is 4K on my PC), then FPS drops from 60 to 20. So I would leave this setting only for the user choice and in all quality presets set it to Normal. What do you think @eordano?
