### ISSUE TITLE
Add validation to detect duplication in Addressables

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#4366]
#### Description

With moving more assets to addressable, we need to have a  validation mechanism to detect duplication resulting in build size and memory usage increase.
We should investigate adding a validation test to the CI, and fail when we detect asses being duplicated in the bundle.

We should have some filtering system to skip checks for some specific asset type, i.e shaders.
We should be able to target specific bundles for the validation, i.e only build-in assets.

For validation, we can use Addressables Editor API, as Unity uses for writing build-in analyze rules.

#### Acceptance Criteria
- [ ] Validation test added to the build pipeline
- [ ] CI failing if detect duplication in assets

**Comment by m3taphysics** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstream-Core-Experience-63aaac346e1c8d00104586e8/issues/decentraland/unity-renderer/4366?planning-poker) with Zenhub @mikhail-dcl @AjimenezDCL

**Comment by m3taphysics** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstream-Core-Experience-63aaac346e1c8d00104586e8/issues/decentraland/unity-renderer/4366?planning-poker) with Zenhub @Kinerius

**Comment by popuz** [comment]
There are two ways to achieve this:
1. To use same Rules that are used in **Addressables Analyze** window, such as `CheckResourcesDupeDependencies`, `CheckSceneDupeDependencies `and `CheckBundleDupeDependencies `classes. **Pros** - minimal to zero maintenance work on Unity updates, because Unity will support this debug window and need to keep this high-level rules up-to-date; - easy to guide for a fix (re-direct developer to **Addressables Analyze** window). **Cons** - slower test time because it involves some Editor UI support (progress bars, messages, etc); - pre-defined output format; - no possibility to exclude bundles or file-types before the test, we can only filter them after test is done.
2. Write test based on the logic inside mentioned rules, which means copy-paste of they functions and removing un-needed parts. **Pros** - potentially faster execution of tests; - filtering before the run of the test; **Cons** - maintenance (if Unity change some API, we will need to re-adjust tests logic to it); - a little bit more of initial efforts

**Comment by popuz** [comment]
For now, I would go for the first approach and check if it takes too much time on the CI.

**Comment by popuz** [comment]
some useful links 

- https://docs.unity3d.com/Packages/com.unity.addressables@1.20/api/UnityEditor.AddressableAssets.Build.AnalyzeRules.html
- https://github.com/Unity-Technologies/Addressables-Sample/tree/master/Advanced/CustomAnalyzeRule/Assets/Samples/Addressables/1.20.0/Custom%20Analyze%20Rules/Editor
- https://forum.unity.com/threads/use-addressables-analyze-tools-in-code.1289162/
