### ISSUE TITLE
New onboarding scene is not properly converted to asset bundles

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#4558]
When launching new onboarding, the assets on the scene are not converted to asset bundles, resulting in a longer load.

![image (16).png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/dd243eba-071e-48be-b045-27c73f701a7a)

**Comment by Kinerius** [comment]
With the new [CDN feature flag](https://play.decentraland.org/?ASSET_BUNDLES_DOMAIN=https%3A%2F%2Fab-cdn.decentraland.org&ENABLE_AB-NEW-CDN=&realm=dclonboarding.dcl.eth&position=5%2C-2) the request is wrongly formatted:

Its 
https://ab-cdn.decentraland.org/manifest/urn:decentraland:entity:bafkreicdminb5uh74p3p3htt5qnzcg5r5lti3fx5pwlv56h4wyckvtndc4?baseUrl=https://worlds-content-server.decentraland.org/contents/.json

Instead of
https://abcdn.decentraland.org/manifest/bafkreicdminb5uh74p3p3htt5qnzcg5r5lti3fx5pwlv56h4wyckvtndc4.json

---

This scene is not converted with the old AB converter

**Comment by Kinerius** [comment]
This was closed automatically by the PR but the issue is still not fixed until we enable the new cdn flag.
