### ISSUE TITLE
Review consequences of inability to load avatars

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-renderer#4755]
**Abstract**
Null (not initialized) fields cause troubles in random places in the code that are very hard to track and fight.
Those can be not only failures but significant delays due to asynchronous nature of loading.

**Acceptance Criteria**

Review 2 following cases:
1. `UserProfile.avatar` is not loaded [yet] but used in views and other places in the code
2. Avatar Load Failed for other users, how it affects interaction with them

Review how repetitions are done and whether recovering gracefully from a not-loaded avatar is possible.
As a result, discuss and establish rules that will make the overall behavior clean and clear if avatars are not loaded.

**Propositions:**
1. Manually simulate loading failure (hardcode) and observe the consequences

**Comment by popuz** [comment]
summary of consequences [ is here ](https://www.notion.so/decentraland/Consequences-of-inability-to-load-UserProfile-Avatar-0314e17091ae42d79a1728850336f989). Inability to load user profile looks more critical, since it breaks loading process. While, problems for other users profiles is not fully breaking, but could be connected with several `NullReferences` and `OperationCancaled` exceptions that we have in Sentry.
