### ISSUE TITLE
Friend Requests status is getting out of sync

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#4803]
The Friend Requests status is getting out of sync when we open/close the passport.

### Steps to reproduce
1. User A send a friend request to User B through the passport and notice that the friend's button is in REQUESTED mode (it's ok).
2. User A close the passport.
3. User A open the passport again and notice that the friend's button is in ADD FRIEND mode (it's wrong... it should be in REQUESTED mode).
4. User A close the passport again.
5. User B accept the friend request received from the User A.
6. User A open the passport again and notice that the friend's button is still in ADD FRIEND mode (it's wrong... it should be in FRIEND mode).

### Source of the issue
Debugging the issue I noticeconfirmed that the problem comes from the `GetFriendshipStatus` RPC message that is returning a wrong value (specifically the `NONE` value) in the `Status` field.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/f509f07c-9db3-4fd0-aa17-9911294ae432)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/de38eda3-4295-43d0-a542-4ec964a4d13e)

I observe how I firstly send the request to the other user and then I receive the correct status: `REQUESTED_TO`. Then I close and open the passport, and when I get the status again, it is `NONE` (for this reason the button appears as [ADD FRIEND] instead of [REQUESTED].

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/f65b432a-55b5-4a20-8e89-a70d55c98baa)

The difference is that in the first step the info is returned by the `SendFriendRequest` RPC message (it's ok), and in the second step by the `GetFriendshipStatus` RPC one (it's wrong). So I would say the source of the problem is there.

**Comment by Julieta11** [comment]
Findings: 

1. It's not 100% reproducible.

2. Once it starts to malfunction, the problem persists in all subsequent friendship actions between User A and User B, as well as in any other interactions between User A and anyone else.

3. Whenever User A sends a request to User B, the flow should always be as follows:
![image.png](https://images.zenhubusercontent.com/6320b37cdbcfb0eaf66c2633/17138a9a-ce25-4cd7-924d-1fc46fbf22a1)

However, sometimes something like this happens:
![image.png](https://images.zenhubusercontent.com/6320b37cdbcfb0eaf66c2633/3cc1bc12-0c84-42b5-bbda-b8514dd3e88c) 

Whenever scenario number 2 occurs, the status becomes out of sync and malfunctions.

**4. The status returned by the `GetFriendshipStatus()` message is incorrect because the state of friends in Kernel somehow becomes corrupted, which causes the `store.friends.toFriendRequests` and `store.friends.fromFriendRequests` lists to remain empty and not get updated properly.**

5. In the backend, all requests are processed successfully. Therefore, when User A refreshes the session, the statuses displayed are correct.
