### ISSUE TITLE
Debug metric reports of users with FPSCap ON but more than 30 FPS

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#482]

**Comment by davidejensen** [comment]
Metabase query wil all capped session with higher frames: https://metabase.decentraland.systems/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozNiwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsic291cmNlLXRhYmxlIjozODMzLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDEwMzkwMSxudWxsXSx0cnVlXV19fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e30sIm9yaWdpbmFsX2NhcmRfaWQiOm51bGx9

Report functionality:
PerformanceMetricsController.Report

**Comment by davidejensen** [comment]
For what I've seen even by researching online, it's better to avoid setting an `Application.targetFrameRate` on WebGL builds, because it's best to leave the browser handle on its own the max framerate (if hardware accelleration is on), otherwise it could cause big stutters and hiccups during execution.

My proposal is to remove the 30 fps cap option in webgl builds and let the browser decide what's best

**Comment by davidejensen** [comment]
Talking with Pravus gave me a more complete insight at what happens in webgl.
Instead of using the `Application.targetFrameRate` the fpsCap forces the rendering frame to skip some renderings to reach the FPS CAP ( done in https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Plugins/CustomRequestAnimationFrame/CustomRequestAnimationFrame.jspre ).

Because this behaviour has been intensively tested the actual problem could be in the metrics reported functionality ( `PerformanceMetricsController.Report` )

**Comment by pravusjif** [comment]
The FPS Cap was rendered obsolete after we merged this pr: https://github.com/decentraland/unity-renderer/pull/2422

It was based on this theory that proved to be right: https://docs.google.com/document/d/1nH5Jd2T8Mfk2IaS1JqVLKEb3dROfBqcNgp8u6Y9tb4E/edit

So I believe this issue can be closed.

**Comment by davidejensen** [comment]
Yes can confirm the issue can be closed due to FPS cap being removed
