### ISSUE TITLE
MinimapMetadata does not support deletion

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-renderer#4839]
`MinimapMetadata` `Clear` is not called and removal, in general, is not handled in `ScenesOfInterestsController`.

**Comment by dalkia** [comment]
Its relevant to mention work done in #4961 and #4858

#4858 removes the map altogether from worlds. So, the scene info from worlds would never get to the map, so there would be no need for clearing the MinimapMetadata.

#4961 adds the possibility to get a scene's info from a catalyst directly from the world. That would save a scenes metadata into MinimapMetadata, but it would be the catalyst info. So, that's the same information that its gonna be saved when going back to a catalyst realm. So, no need for clearing the MinimapMetadata.

Considering both of these, we could close this issue, since we dont have a reason to clear the MinimapMetadata.
