### ISSUE TITLE
The mouse cross-hair disappears - WORLDs

### ISSUE THREAD

**Issue by Kaze-No-Kai** [decentraland/unity-renderer#4847]
Hi Team,

Nikki Fuego mentioned that the mouse cross-hair disappears a lot in WORLDs and she has to right click then left click to get it back.

Let me know if you need anything from her end,
Stoyan

**Comment by xavi-dcl** [comment]
Is this the same issue as https://github.com/decentraland/unity-renderer/issues/4999?

Or does the cross-hair disappear in more cases? Please add steps to reproduce.

**Comment by kwssbocian** [comment]
Issue occurs on both production and dev branches on all platforms for both wallet and guest login type. Additionally this issue is not limited to just worlds - it occurs everywhere on catalyst realms and worlds alike. It can be easily missed because the crosshair reappears immediately after locking the cursor in the client window.
https://images.zenhubusercontent.com/337227404/2c5cbe24-fc05-4336-96c3-dec5ff761d29/2023_06_23_14_13_45.mp4
