### ISSUE TITLE
Fix NRE with WearableLoader.SetBones

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#5429]
`NullReferenceException: Object reference not set to an instance of an object
AvatarSystem.WearableLoader.SetBones (UnityEngine.Transform rootBone, UnityEngine.Transform[] bones) (at Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/WearableLoader.cs:90)
AvatarSystem.Loader.Load (WearableItem bodyshape, WearableItem eyes, WearableItem eyebrows, WearableItem mouth, System.Collections.Generic.List`1[T] wearables, AvatarSystem.AvatarSettings settings, UnityEngine.SkinnedMeshRenderer bonesContainer, System.Threading.CancellationToken cancellationToken) (at Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/Loader.cs:91`

**Comment by sandrade-dcl** [comment]
It seems this issue started happening the past June 21 and it has stopped from the past Tuesday (July 4). 

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/b8881abd-e3a4-4b06-ba8b-de6ab23824ec)

That means that this was fixed with the this release: https://github.com/decentraland/unity-renderer/pull/5436

We're going to wait a bit more tmie to confirm it, and if so, we can close the issue.
