### ISSUE TITLE
[QA] A bright white light appears on screen for a number of users 

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-renderer#5698]
**Description of the issue:**
In some ocations, while building and adding materials, some users reported a white light appearing on screen that doesn't go away after refreshing. There are no specific repro steps to catch the issue, since it happened in isolated situations.

Some of the reports came from https://play.decentraland.org/?realm=boedo.dcl.eth&position=0%2C0

And for additional info, we have the discussions on Slack:
https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1694433886766899
https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1694103722078469

![image](https://github.com/decentraland/unity-renderer/assets/139157886/cf9f8a7f-bad1-4530-9c10-05d0d0986fc0)

https://github.com/decentraland/unity-renderer/assets/139157886/6b1591df-11a4-47ca-b60e-5ddce329dcb0

**Comment by dalkia** [comment]
The bright light is a result of a bad material forming that got introduced with the latest Unity release. The bright light can be seen only in Mac WebGL, but in other platforms the material is not being displayed correctly. More info on the different results on this [thread](https://decentralandteam.slack.com/archives/C03G496L6NN/p1694792103129199?thread_ts=1694791107.998549&cid=C03G496L6NN). 

The issue seems to occur when a mesh has scale 0 on any of its axis. This can be tested on this test [branch ](https://github.com/decentraland/unity-renderer/pull/5712). You can test it by going to -60, 0 and walking north. There are some lamp posts that should be displaying the DCL logo, but they arent. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazJyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a11d358ecc77d0e1153c2cea78ffd47d6f84abab/image.png)
Correct material displayed

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazZyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a409810c36fe8daf871f452097da2113263c7916/image.png)
Issue in Mac WebGL

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaytyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1dbc8c34b9c4a8d4cba2633c11a7c71e23d12254/image.png)
Issue in Windows WebGL

Since we cannot be playing with the scale of meshes, we should trying fixing the material. [Here is latest Pravus suggestion to try out](https://decentralandteam.slack.com/archives/C03G496L6NN/p1694794847422899?thread_ts=1694791107.998549&cid=C03G496L6NN)
