### ISSUE TITLE
Invalid errors message are sent from kernel#saga context to segment

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#614]
This blocks the team from properly diagnose the funnel drop on first load on the case of errors, as most of errors coming from `kernel#saga` have no valid `Error` objects:
![image](https://user-images.githubusercontent.com/6875814/122109171-72b2ce80-cdf3-11eb-85e0-198f21bad7d7.png)

Related code to start investigating:
https://github.com/decentraland/explorer/blob/master/kernel/packages/shared/store/store.ts#L13:L13

**Comment by kuruk-mm** [comment]
Maybe https://github.com/decentraland/explorer/pull/2433 will fix this problem.

The majority of the 'null errors' are errors from `#35030 RuntimeError: memory access out of bounds`, and we can saw them in Rollbar. https://rollbar.com/decentraland/World/items/35030/?item_page=0&#traceback

So, maybe the problem is that errors that are not `Error` instead will not be shown.

Meanwhile, the `#35030 RuntimeError: memory access out of bounds` errors are mainly users trying to enter a Mobile Navigator. They will see that `Mobile is not supported`, but we load Unity and everything as normal in the background. So we must stop the system load after we show the `Mobile is not supported` screen.

Another observation is that the errors from the context `renderer#errorHandler` must shut down the app because we end with false errors in the `kernel#saga` context.

**Comment by kuruk-mm** [comment]
Confirmed that https://github.com/decentraland/explorer/pull/2433 fixed the problem
