### ISSUE TITLE
BiW publishing scenes should remove soft linking with Project

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#618]
There is a soft link between the Land and the Project, for those projects that were created from Builder in-world.

This relationship should be broken at the moment the Project is published in the Land, becoming a relationship between the Project and the Scene.

If in any case this relationship continues to exist, it will be removed during the unpublish of the scene.

In any case, when a scene is unpublished, the Land will NEVER maintain a link to a previous Project.

**Comment by olavra** [comment]
This is not solved. Steps to reproduce:

- Go to an empty land
- Edit it
- Publish it
- exit the editor
- Unpublish
- Enter the editor again
- The project is still linked

**Comment by Suduck** [comment]
It also should do it at the unpublish time, because:

1. you can start a scene in builder in world
2. Then go to builder, create a new project
3. Publish the new project created from builder
4. Unpublish the new project created from builder
5. It should create a new project and not get the first created scene

**Comment by sandrade-dcl** [comment]
The decentraland/explorer#2442 change also introduced the **next bug**:

Always we publish a scene from the BiW Editor, the status of the project in https://builder.decentraland.io is not being updated correctly, it always stays with the orange dot, when it should pass to the green one.

#### Steps to reproduce:
1. Publish a scene from BiW editor.
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/729436d3-4970-4f31-a40a-60614324351c)

2. Go to https://builder.decentraland.io and notice that the status of the project is wrong. It should be green instead of orange.
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/6d80bf1d-4abd-45ec-a639-8fe90b2c97fd)

Investigating, I have noticed that the bug was introduced when the call to `await this.updateProjectDetails(sceneState, sceneName, sceneDescription, thumbnailBlob)` in `SceneStateStorageController.ts` was moved from the start of the `publishSceneState()` function to the end.
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/394610ea-6955-4cd0-bf39-033d62b6f147)

If we move back the `await this.updateProjectDetails(sceneState, sceneName, sceneDescription, thumbnailBlob)` to the old place, the bug is fixed. But we need to confirm it with @pbosio, I don't know if this change could affect to other change he applied in his PR.

**Comment by pbosio** [comment]
You can move that line back up (please, if you choose to do this, put it inside a try/catch)
keep in mind that saving before publishing there might be an issue if publish failed: project coords will be unlinked but scene won't be deployed.
other option could be doing something like `const projectUpdateTime = new Date().toISOString()` before publishing and puting that value to the project manifest `project.updated_at` (that is set at function `updateProjectManifest(builderManifest: BuilderManifest, identity: ExplorerIdentity)`)

**Comment by Suduck** [comment]
This is handle correctly in the new publish flow by Unity, it will only unlink the project if the publish has been succeed
