### ISSUE TITLE
Far-away scene objects can appear in current player position

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#638]
@nearnshaw reported that it looks like **some entities are appearing not just outside the scenes they should be in, but they’re being loaded KILOMETERS AWAY from the scene they belong to**.

They don’t appear consistently always, but when clearing cache it looks like it gets fixed.

It doesn’t happen everywhere, it looks like it only happens with the casino scenes and especially with the new under the sea casino that they’re about to release.  This scene is not published for everyone, it checks the player id against a whitelist and only renders things when you’re in the list. So to see this inaction, **contact @nearnshaw to be whitelisted into the scene**.

**Once whitelisted, steps to reproduce:**
1. Visit the new casino: https://play.decentraland.org/?position=-139%2C127&realm=fenrir-amber
2. Walk outside, about 50% of the time you’ll already see a fish model outside, rendered in a road parcel that is a separate scene. If you don’t see it, reload a couple of times till you do:

![image (6).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/cbc4e193-9917-4361-aec4-987b470853a2)

The entities can load **even farther away**. After visiting that scene, if you go to genesis plaza, you might also see the fish on the ground in the middle of the bar, keep in mind that the scene this fish belongs to is at `-138, 127`. Nothing from that scene should be rendered when you’re in genesis plaza:

![image (7).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/f74502d5-4299-4380-bb38-22acef3ae65c)

Also it seems that in the same spot in front of the casino where you see the fish, you can sometimes see a casino slot machine. This slot machine isn’t used anywhere on the casino you see infront. This machine belongs to the Tominoya casino, that’s also very far away:

![image (8).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/5c386360-1492-4f00-b200-04084d08de90)

We've only seen this issue with the casino scenes, it might be something wrong on the scenes code. But clearly this exposes a big vulnerability that could be maliciously exploited, and could even be a clue to how to optimize the use of memory.

**We should debug wha's going on there, maybe they are appearing in the unity-world 0,0 position as it used to happen a long time ago?**

**Comment by Suduck** [comment]
I think that this issue is relate to #389 from builder in world, The issue comes from the Object Pool! 

I think that the problem comes when an object is not initialized correctly in the poolmanager and it is not deactivated. I has been able to reproduce it with a builder in world object

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/70411a0e-f256-4fa7-ab50-641169a7a2d0)

This item should have a collider but the collider component doesn't exists

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/470af59b-e825-445c-9150-d0f7ce7f58f8)

As you can see there is another object with the collider,

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/d7104475-27aa-44d0-9d43-0a7273e55012)

**Comment by AjimenezDCL** [comment]
This PR: https://github.com/decentraland/unity-renderer/pull/746

Should fix the issue.
