### ISSUE TITLE
Show warning notification for not recommended browsers

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#708]
We have decided not to have a "black list" of prohibited browsers and only deny browsers due to technical limitations such as not supporting WebGL2. If an user enters with a browser that is compatible with WebGL2 but not recommended by us (any browser different to Firefox or any not chromium-based browser), we will show him a warning in the landing page indicating it but we won't cut his entrance to the world.

**Comment by BrianAmadori** [comment]
It seems that the latest Safari version can't reproduce the issue (on windows).

**Comment by sandrade-dcl** [comment]
We can't check the browser detection to show the corresponding error screen in a proper way because there exists a race condition in the kernel side where the website loading and the react app loading are happening in pararel (that's why some browsers like Saffari are giving an error when getting the store). Agus Mendez is currently working on a refactor on this side, it will be ready this week.

**Comment by sandrade-dcl** [comment]
On the other hand, I think we should re-design the requirements for this issue because DCL is working well in more browsers than we thought it would (Edge, Brave, new versions of Safari, Firefox, Chrome...). To limit our app to only 2 browsers could be counterproductive.

**Comment by menduz** [comment]
Hello, I'd like to know what specific things make a browser compatible or incompatible. 

To prevent falling into the [IE6 fallacy](https://www.theverge.com/2018/1/4/16805216/google-chrome-only-sites-internet-explorer-6-web-standards). Making allow lists for browsers is considered a bad practice and I wouldn't do unless we have no other option.

As an example, extending what Santi said, I use brave for DCL, and it works _perfectly_ there. Way better than firefox to be honest. I also tested it in Edge and works like a charm. And even though the latest Safari with WebGL2 is compliant and every use case works, the experience is still bad enough to not be usable.

**Comment by sandrade-dcl** [comment]
Yeah, I agree with that. In fact, all browsers that imlement chromium (I guess Brave and even Edge are examples of this) will work well.

After open the discussion in my team, we have come to the conclusion that we shouldn't limit any browser and, if we want to have a list of "recommended browsers", ok, but we would only show a warning message giving the recommendation to the user. What do you think about this solution, @menduz? If we go through this line, we would need to design with @RominaMarchetti how and where we are going to show this warning.

Anyway for me, I wouldn't limit any browser neither show any warning. We already have all our metrics with the browser info injected and we would be able to separate the possible errors by browser, so...

**Comment by sandrade-dcl** [comment]
As I discussed with @menduz:

- **ERROR ON SAFARI (VERSIONS LOWER THAN 14)**: We are going to wait for the website/kernel refactor to be integrated. Once it is ready, we shouldn't get the Safari error due to the race condition metioned in the previous comments.

- **BROWSERS LIMITATIONS IN OUR APPLICATION**: We have decided not to have a "black list" of prohibited browsers and only deny browsers due to technical limitations such as not supporting WebGL2. If an user enters with a browser that is compatible with WebGL2 but not recommended by us (any browser different to Firefox or any not chromium-based browser), we will show him a warning indicating it but we won't cut his entrance to the world.
