### ISSUE TITLE
Casino roulette chips OnPointerEvent issue

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#839]
Slack thread link:
https://decentralandteam.slack.com/archives/CS8SCNYUV/p1626904161134700

From the Decentral Games team:
> We've been having a strange issue with one of our Roulette tables in the Tominoya Casino in production. Whenever someone goes near to it and tries to play in in, whether with Crypto or with Free play, as they try to put their chips down, nothing happens, and they can never place the chips. We have found the same issue on the Testing env, but other tables work normally, so we'd like to consult with you, as we believe this might not have to do with our code per se. 

My take on this bug:
> We had similar issues with the blackjack tables on the past. It seemed to happen very randomly, we did apply some defensive fixes but I think the bug may not be fixed 100%. Specifically it was related to using `OnPointerEvent` with `GLTFShape` colliders. In the blackjack table case you were able to work around it by using an `OnPointerEvent` attached to an invisible `PlaneShape` (or `BoxShape` , basically any parametrizable shape) on front of it.

How to reproduce it:
>it now has a bigger repro rate, for instance right now I've reviewed it again in production as I did yesterday.
Try joining and later trying to place the chips on the roulette tables that are in this sector of slots:
https://play.decentraland.org/?position=-123%2C134&realm=loki-amber
And then compare it to the ones in this sector:
https://play.decentraland.org/?position=-121%2C136&realm=loki-amber
At least, for me right now, I can repro the issue on the tables in that particular sector of slots.

![image](https://user-images.githubusercontent.com/6875814/126678033-863b572d-ee9d-45e9-b5c7-434436dd6470.png)

![image](https://user-images.githubusercontent.com/6875814/126678052-5e350ec0-9537-48b8-b81e-fe963cc71bcd.png)

**Comment by Suduck** [comment]
I have investigated this issue and I have found that there are two entities in the exact same position with colliders. 

On one hand, we have the entity `Enm `with a normal collider

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/340936b4-9e22-4522-8ecb-a4d75b1c7f39)

On the other hand, we have the entity `Enn` with lots of `OnPointerEventCollider` 

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/ea938eca-c8fc-401c-800e-ff74c6e95b65)

The `OnPointerEvent ` is blocked by any collider found in its way. In this case, due to the floating-point error sometimes the normal collider is detected before the `OnPointerEventCollider`, blocking the raycast to the `OnPointerEvent`

In order to make this work 100% of the times, we recomend to remove (or move down a little bit) the normal collider so we can ensure that the colliders are called in the same order always
