### ISSUE TITLE
Remove invisible blocking UI in center of the viewport

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#912]
Apparently we introduced some kind of invisible vertical UI that blocks UI interactions in the center of the viewport as shown in the screenshots.

The report from Decentral Games QA person is as follows:
>We are trying to implement a new Tournament UI and this is causing the area in the center to be unclickable in the middle, but as our design has a centered button, to access the competition, this is an important hurdle to resolve. Obviously this also still happens in any popup still.

![image (12).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/1f9166b1-28bb-474c-9741-db54523c4d2e)

![image (13).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/973137c9-6617-4e7b-89d8-194c1b43fc43)

The "Cursor" UI Image we use for the crosshair is not a "raycast target" so that shouldn't be the problem.

**Comment by Kinerius** [comment]
I made a test scene with a big button that reproduces a sound when clicked. I found no invisible blocking UI

Is there any step to reproduce this issue?

**Comment by Kinerius** [comment]
The issue can be tested here:

https://testing-decentral.azurewebsites.net/?ENABLE_WEB3&SCENE_DEBUG_PANEL&position=-120%2C136&realm=localhost-stub

I was able to find a clue by turning off UI elements (of that scene) one by one until I was able to click the `Skip Tournament` button and then the `Enter Tournament` button with another UI element turned off.
It seems there are some texts and images from that scene UI that is blocking the input.
I'm 100% sure this issue is not on our side

Decentral Games is now working on this
