### ISSUE TITLE
NPC animations get stuck in a loop

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#985]
Sometimes an entity with multiple animations gets stuck playing an animation in a loop. When this happens, you can't call the entity to play any other animations, even when you interact with the entity.

This seems to happen mostly in large scenes. It's not deterministic, in all the places where I see it happen it's just sometimes. Might be more common on slower machines.

In genesis plaza I see it a lot, the bar tender gets stuck quite often in a short animation. He should also switch animations when you talk to him, but he's stuck in a loop. There are also other places where I see this less often.

I think every time I saw this, it was with entities that aren't loaded with the initial load of the scene. In this case, the bar tender is only loaded when you go downstairs.

This happens both in preview and in production.

My theory is that the entity is never getting the Animator component loaded, and the default behavior when no animator is present is to loop the first animation.

https://images.zenhubusercontent.com/337227404/c67b8ff0-ac1d-4c57-816e-8455bdc77df3/screen_recording_.mov

**Comment by olavra** [comment]
I was able to reproduce this issue while playing the quest "Drink of the gods" in the zone environment

**Comment by Suduck** [comment]
I have investigated this issue.

This issue seems that is not related to the animation system itself but with the way the NPC are created in the genesis plaza.
I have downloaded the scene of the genesis plaza and I have noticed this code in the npc file 


  octopus = new NPC(
    {
      position: new Vector3(160, 0.2, 141.4),
    },
    'models/core_building/BobOctorossV44.glb',
    () => {
      if (octopus.getComponent(NPCTriggerComponent).onCameraEnter) {
        octopus.getComponent(NPCTriggerComponent).onCameraEnter = undefined
      }
      octopus.changeIdleAnim('TalkLoop')
      octopus.playAnimation('TalkIntro', true, 0.63)
      octopus.talk(OctoHi)
    },
    {
      portrait: `images/portraits/bartender.png`,
      dialogSound: `sounds/navigationForward.mp3`,
      idleAnim: 'Idle',
      faceUser: false,
      darkUI: true,
      onWalkAway: () => {
        backToIdle()
      },
    }
  )
  
  

The last parameter is a NPCData and it seems that it set the animation of idle to the correct animation.
It seems like the problem is there because there information is no reaching unity (I don't know why yet)
so it plays the first animation which is "TalkOutro" in a loop.

The 3rd parameter is a function with the next explanation: "Function to execute each time the NPC is activated. By default when clicking it or walking near, or calling the `activate()` function". This function is not activated either so this decreases the chances of the bug being cause from the animator

We will need to investigate this further to have a better understanding of how the npcs are implemented and see why this is happening to identify the root of the issue

**Comment by olavra** [comment]
@nearnshaw this seems to be related to the scene

**Comment by olavra** [comment]
@nearnshaw ping

**Comment by nearnshaw** [comment]
I'm 100% sure the problem is not remates to the scene

It only happens sometimes, randomly. Sometimes the scene loads well, with exactly the same code
I've also seen similar things in many other scenes for a very long time

Even if the code of the scene was calling the wrong animation or something, the animations never change, even when a lot of your interactions with the npc should change them.

My theory is that by some race condition, the Animator component is never added. So what we see is the default behavior of an entity w no Animator component : it loops the first animation

**Comment by nearnshaw** [comment]
> The 3rd parameter is a function with the next explanation: "Function to execute each time the NPC is activated. By default when clicking it or walking near, or calling the activate() function". This function is not activated either so this decreases the chances of the bug being cause from the animator

The activate function is being activated correctly. Otherwise the npc wouldn't talk.

What I did in this particular npc, so that it doesn't get too annoying, is have it activate by proximity only the first time you approach it. Then you only can activate it by clicking. Maybe that generated confusion
